(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"murillo_finalProject_atlas_1", frames: [[0,0,1467,695],[0,697,613,110],[615,697,475,121],[1092,697,345,121],[297,809,278,121],[0,809,295,121],[1469,0,547,890]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_37 = function() {
	this.initialize(ss["murillo_finalProject_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_36 = function() {
	this.initialize(img.CachedBmp_36);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,8000,2166);


(lib.CachedBmp_35 = function() {
	this.initialize(img.CachedBmp_35);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,6658,1776);


(lib.CachedBmp_34 = function() {
	this.initialize(img.CachedBmp_34);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,7770,1698);


(lib.CachedBmp_33 = function() {
	this.initialize(ss["murillo_finalProject_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_32 = function() {
	this.initialize(ss["murillo_finalProject_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_31 = function() {
	this.initialize(ss["murillo_finalProject_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_30 = function() {
	this.initialize(ss["murillo_finalProject_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_29 = function() {
	this.initialize(ss["murillo_finalProject_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_28 = function() {
	this.initialize(ss["murillo_finalProject_atlas_1"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_27 = function() {
	this.initialize(img.CachedBmp_27);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2655,1191);


(lib.CachedBmp_26 = function() {
	this.initialize(img.CachedBmp_26);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,2131,751);


(lib.CachedBmp_25 = function() {
	this.initialize(img.CachedBmp_25);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,3106,878);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.sun1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFCC").s().p("AnFHGQi8i8AAkKQAAkJC8i8QC8i8EJAAQEKAAC8C8QC8C8AAEJQAAEKi8C8Qi8C8kKAAQkJAAi8i8g");
	this.shape.setTransform(64.2,64.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.sun1, new cjs.Rectangle(0,0,128.4,128.4), null);


(lib.rabbit = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,255,255,0.988)").s().p("AjbO9QidiWAAjUQAAjVCdiWIADgDQgagjgeg6IjSmVQiBj6hBi8QhAi8CtALQCtALBRCeQBRCdA/DsQA/DsAJCwIABA1QByg8CMAAQB1AABjApQgWgpgRhkQgdirAAjyQAAjxAdirQAdirB/hIQB/hHAdCrQAdCrhVE5QhWE5geCrQgXCJgfAbQA+AhA2A0QCdCWAADVQAADUidCWQidCWjeAAQjcAAidiWg");
	this.shape.setTransform(69.401,110.6709);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.rabbit, new cjs.Rectangle(0,0,138.8,221.4), null);


(lib.pic = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF6600").ss(9,1,1).p("AhakNQAKgCALgBQAxgHBBgJQAYgDAOABQAUAAAPAJQAbAQAKA0QAVB0gnCMQgbBghHCXQgTAAgKABQiEjggmkGQgFgiAKgRQAJgOASgGQASAAAUgDgAiAkKQAFgBAFgBQAMgCAQAB");
	this.shape.setTransform(45.0061,89.4639);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#6699FF").ss(10,1,1).p("AnEqkIOJAAIAAVJIuJAAg");
	this.shape_1.setTransform(45.325,67.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FF6600").s().p("AigjDQgFgiAKgRQAJgOASgGQASAAAUgDIAVgDIBygQQAYgDAOABQAUAAAPAJQAbAQAKA0QAVB0gnCMQgbBghHCXIgdABQiEjggmkGg");
	this.shape_2.setTransform(45.0061,89.4639);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#003300").s().p("AgWBxQgMgEgVgLQgFgCgCgFQgDgEAEgDQgngLgSgSQgZgZgCgvQgBgWAIgJQAHgJASgDQASgCATAHQARAHANAOQAEglAMgTQAIgNANgHQANgIANACQAPACAJANQAKAOgGANQAVgeA5AGQAMACAEAEQAHAHAAAPQABAbgLAgQgGAUgRAkQgKAWgJAKQgMANgdAOQgYAMgRACIgGAAQgNAAgPgFg");
	this.shape_3.setTransform(40.6706,48.1941);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AnEKlIAA1JIOJAAIAAVJgAiegdQgKASAFAhQAmEHCEDgIAdgBQBHiXAbhgQAniNgVh0QgKgzgbgRQgPgIgUgBQgOAAgYADIhyAPIgVADIgHAAIgBAAIAAAAIgRABIgDABIgKACQgTAGgIANgAigj/QgRADgIAIQgIAKABAWQADAwAZAZQARASAnALQgEADADAEQADAEAEADQAWAKALAEQATAHAQgBQARgCAYgNQAdgNAMgNQAIgKAKgWQARgkAHgVQAKggAAgbQAAgQgIgGQgEgEgMgCQg4gGgVAeQAFgNgIgOQgJgNgPgCQgOgCgOAHQgMAIgJANQgLATgEAlQgNgOgSgHQgOgFgPAAIgIAAgAh5gyIADgBIARgBIAAAAIABAAIAHAAQgUADgSABIAKgCg");
	this.shape_4.setTransform(45.325,67.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.pic, new cjs.Rectangle(-5,-5,100.7,145.4), null);


(lib.head = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// eyes
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhzBGQgagFgTgTQgUgUgcgEQgbgDAqgKQAsgKAbABQAbAAATAIQATAKAAAMQABAMgQAQQgOAMgVAAIgIAAgACLAEQgSgEgHgJQgFgJAJgMQAIgNARgJQASgJAkgGQAjgHgSALQgRALgEAVQgEATgPALQgLAHgMAAQgGAAgGgCg");
	this.shape.setTransform(7.3922,33.402);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AhvBCQgagEgTgNQgUgOgcgDQgbgCAqgHQAsgIAbABQAbAAATAGQATAHAAAJQABAIgQALQgNAJgVAAIgJAAgAB9AEQgHgEAGgLQAGgMAPgKQAPgLAigOQAggOgPANQgOAMAAAPQgBAPgMAMQgNALgUACIgDAAQgQAAgHgEg");
	this.shape_1.setTransform(6.9649,32.7783);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AhxA4QgZgCgUgIQgUgJgcgBQgbgBArgFQAsgEAbAAQAaAAATAEQAUAEAAAFQABAFgRAHQgNAFgUAAIgKAAgAB6gBQgGgDAHgHQAGgJAPgIQARgJAigLQAggNgPAKQgPAJgCAKQgCALgNAIQgOAJgTADIgPABIgKgBg");
	this.shape_2.setTransform(7.1008,32.7589);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("Ah+A3QgLgBgVgHQgMgCgaAAIgGgBQgDgBAAgEQAAgEAIAAQAcgBAOADIAVAFQAJACARAAIANgBQAOgBAJgEIAHgCQADgBACADQADAFgGAEIgJAEIgJABIgJACIgGABgAB1gCQAAAAAAgBQAAAAAAgBQAAAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAQAAAAABgBQAAAAABAAIAFgBIAFgCQAEgCAJgCIAHgDIAJgCIAFgCIAFgDIAEgEIAOgOIADgEIADgBIAFgFQAFgCACAFQABAEgDACQgBADgDACIgUAUIgEAEIgFACIgFADIgKACIgHADIgIACQgLAEgGAAQgGAAgBgDg");
	this.shape_3.setTransform(7.6643,32.7464);
	this.shape_3._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},6).to({state:[{t:this.shape_2}]},2).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_1}]},2).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape}]},1).wait(9));
	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(9).to({_off:false},0).wait(3).to({_off:true},2).wait(11));

	// head
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AgzJYQgPgKgLgIIAAAAIgEgFQgYgggVg6QgKgegEgRQgKguADgwQADgcAFgUQAGgaAKgaQACgGADAAIABAAQAHAHgGATIgIAUIAAADIgBAEQgCAJAAAFIgBABIgBAIIgBABIAAACIgEAOIgCAWQAAAnACAMQABANAEAPQAGAaAGAUQAWBEAzAzIAGAGgAhmDjIgGgGQhkhxg4iIQgPgkgPgvQgUg8gIgfQgNg7gChKQgCguAEhaQABgOAFgGQAGgIAQgCQAkgGAnAWQATAKAlAlQA5A3AYAeQAlAvAfBBQATApAdBQIAzCHQAPAoAFASIABADIAGAdIACAdQAAAWgOACIg8ikQglhsgZg5Qgphagzg/Qgsg3g6grQgRgNgLgEQgSgGgkAFQgFAsADAwIAAABIAAACQAHBwAxCEQBACmBiBpIAMANQAQATAFALQAGANgCAMQgBAPgKAJIghgjgAC2BaIgDgQIgCgLQgfiqgFhaQgIiNAbiGQAOhEAVgjIAAgBQAGgJAGgGQAKgLALgCQAQgCAPAPIAJAJIAEAHQAPAXAOApQAaBWAIBwQAFBFgBCGIgCBQQgCAsgHAjQgDAXgIAYIAAABIAAAAIgBADIABgCIAAAAIAAABIgEAFQgHgDgCgMIAAgBQgCgJAAgKIACgWIAIgqQAHgiAAhIQABhsgDg+QgFhOgNhBIAAgBIAAgBIgFgXIgCgIQgOg1gWgeQgKgOgLgBIgCAAQgOgBgMAUQgOAXgIAhQgGAVgHAoQgJA8gDAeQgGBMANBlIAbCrIABADQADASABANIAAAIQgCAUgIAMIgCADIgFgQg");
	this.shape_4.setTransform(-21.4121,-5.8871);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFCCFF").s().p("AgtETQgJgMgNgTQgegtgihEQgOgagOgeQgyhqgehYQgehYAIgSIABgCQAJgNAoA8QAcArAgA+IAfBBQAzBpAeBYQAeBYgIASIgBACQgBACgDAAQgIAAgPgSgADgCZIgEgfQgDgjgCgqIgChaIAAgEIAAAAIAAgDIAChcQACgqADgjQAIhHAKAAQAGAAAEASQAEASAEAjQADAjADAqIABBbIAAAEIgBBcQgDArgDAkQgHBHgLAAQgIAAgGgog");
	this.shape_5.setTransform(-20.8342,-18.7711);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AihIRIgEgDIgEgDIgJgIQgzgzgWhEQgHgTgGgbQgDgOgCgOQgCgMAAgmIADgWIAEgPIAAgBIAAgBIACgJIAAAAQAAgGACgJIABgEIABgCIAIgVQAGgTgIgHIAAAAQAEgKAFgJIAGAHIAiAiQAJgJACgOQABgNgFgNQgGgLgQgSIgMgNQhhhphAimQgyiFgHhwIAAgBIAAgCQgCgvAFgsQAkgGASAGQALAEARANQA6AsAsA3QAzA/AoBaQAaA4AmBsIA7ClQAOgDAAgWIgBgcIgHgdQApgLArgBIACAKIADAPIAEAQIACgCQAJgNABgTIAAgHQAAgNgEgSIAAgDIgcitQgNhkAHhNQACgeAKg8QAGgoAGgVQAIggAPgYQAMgUAOABIACABQAKABAKAOQAXAdANA2IACAHIAFAXIABACIAAABQANBAAEBOQAEA/gBBsQgBBHgHAkIgIApIgBAWQAAAKABAIIABACQACALAHAEIAEgFIAAABIABAAIAAAAIAAABIADACIABACIACACIABAAIAAABIABAAIAAABIABAAIABACIABABIABAAIABABIABAAIAAABIABAAIABABIgBAAQgEAAAAAEQgCADACADQACAEAIAEQA0AbAzBBIALANQAmAvAZAwQAcA1AOA5QAFASADATIgqAPQgQAFgEAJQAIABAOgGIApgQIAEAoIgDABQgRADgYAAQgHAAgDACQgCACgDAGQAWACAggFIAGgBIAAAPQABAsgPAWIgEAGQgGAHgJAHQgMAIgRAJQhLAjhiAMQg3AGhGgCIAAABQgBACACADQiMgdhkhIgACkHnIgcANQgwAYhFAVIgTAGQgKADgOAHQgPAHgCAJIBBgYQAXgHAugSIAegNIAdgOQAQgHANgCIAHgCQADgCACgGIgCgBQgMAAgPAGgABvHEQgcADgvAJQgsAJgYAKQgMAGgXANQglAUgMASQAugdASgKQAZgMAcgIIAugKIAtgHQAngGAxABIAGgJQgOgBgPAAQgWAAgYADgADhGyQgEABgCADQgBADAEACQADABADAAQAcAGAdASIACABQgBAEABACIABAEIABAUQAAAGACABQADABACgBIAEgDQABgBAAgHIgBgUIgCgFQACgCACgFQACgFAHgIIAKgNIACgHQgBgFgDAAQgEgBgFAGIgDAFIgBAAIgIACQgKADgMgBIgUgCIgGAAQgLgEgIAAIgGABgAmEm3IgBABQgIASAeBYQAdBZAzBqQAOAeAOAbQAiBDAeAtQAMATAKALQAUAaAHgKIAAgBQAJgSgfhXQgehYgyhrIgghAQggg/gbgrQghgxgMAAQgDAAgBADgABcmxQgEAjgCAqIgBBbIAAADIAAABIAAADIABBbQACAqAEAjIAEAfQAGAoAIAAQAKAAAHhHQAEgjACgrIACheIAAgDIgChbQgCgqgEgjQgDgkgEgSQgFgSgFAAQgLAAgHBIgAHBG7IgCgSIADAJIgBADIABAGgAEVBZIAAAAIAAAAIAAAAgAEUBYIABAAIAAABIgBgBgAEUBYIAAAAIAAAAIAAAAIAAAAgAEUBYIgBgBIABAAIAAABIAAAAgAETBXIAAAAIAAAAIAAAAIAAAAgAETBXIgBgBIABAAIAAABIAAAAgAESBWIAAAAIAAAAIAAAAIAAAAgAEQBVIAAgBIABAAIAAABIAAAAIAAAAIABAAIAAABIgCgBgAESBWgADuA4IABAAIABABIgCgBgADtA3IAAAAIABAAIgBAAgAC2AOIAAAAIABABIgBAAIgBABIABgCg");
	this.shape_6.setTransform(-7.9667,2.4976);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("Ah0EtIgpgGQgCgDABgCIAAgBQBGABA3gGQBhgLBLgkQARgIAMgJQAJgHAGgHIAEgFQAPgXgBgrIAAgQIgGABQggAGgWgDQADgGACgCQADgCAHAAQAYAAARgCIADgBIgEgoIgpAPQgOAGgIAAQAEgJAQgFIAqgPQgDgTgFgSQgOg4gcg2QgZgvgmgvIgLgOQgzhBgzgbQgIgEgCgEQgCgCACgEQAAgDAEgBIABAAIAAABIABAAIABAAIABABIABAAIANAKIABAAIADACIABAAIABAAIAAABIABAAIAAAAIABAAQAAABAAAAQAAAAAAABQAAAAABgBQAAAAAAAAIABABIABAAIABABIABAAIAAABIABAAIAAAAIAAABIACABIAAAAIABABIABAAIAAAAIABAAIAAABIAAAAIAAAAIABABIAAAAIAAAAIACACIAAAAIABABIALAIIAJAHIgBABIABAAIAAAAIAAAAIAAABIABAAIAAAAIAAAAIAAABIABAAIAAAAIAAAAIAAABIABAAIAAAAIABAAIAAABIAAAAIAAAAIABAAIAAABIAAAAIAAAAIABAAIAAABIABAAIAAAAIAAAAIAAABIABAAIAAAAIABAAIAAABIAAAAIAAAAIABAAIAAABIABAAIAAAAIAAAAIAAABIAAAAIACABIAAABIABAAIAAABIABAAIAAABIABAAIAAABIABAAIAAABIABAAIAAABIABAAQATATATAXQApAxAdA1QApBLAOBSIA2gTQBHgYBBgOQgBAHgHADIgNAEQgkAHg0ARIgzAQIgdALIADAXIACATIABAAIAMgDIAagDQAJgBANgDIAWgGQAegIAcAAQgDAHgDACQgDACgEgBQgJAAgLACIheASQgBACgFABIgIACIAAAFQABAHgDAWQgFAkgJAPQgDAHgHAHIAAABIAAAAIgBADIgCABIAAACQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAAAQgBABAAAAQAAAAAAAAQAAAAAAABIgFADIgBABQgBAAAAAAQAAABAAAAQgBAAAAAAQAAABAAAAIgCABIgCACIgHAFIgEACIgCAAIgBACIgCAAIgdANIgfANIgIACIgPAFQgbAJgRAEQgQAEgMACQgUAEgpABIgPABQgWAAgPgDgAkFDhQAOgGAKgDIAUgHQBFgUAwgYIAcgNQAQgGANAAQgCAHgDACIgHACQgNABgQAIIgdAOIgeAMQguASgXAHIhCAYQACgJAPgHgAmLDZIAAgBIABABgAkwCmQAXgNAMgFQAYgLAtgIQAvgKAcgDQApgFAiAEIgGAJQgxgBgnAFIgtAIIguAKQgdAIgZAMQgSAJguAeQAMgTAlgUgAA2CqQgCgBAAgFIgBgUIgBgEQgBgCABgEIgCgBQgdgTgbgFQgDAAgDgCQgEgCABgDQACgCAEgBQAJgCAPAFIAGAAIAUABQAMABAKgDIAIgCIABAAIADgEQAFgGAEAAQADABABAEIgCAHIgKANQgHAIgCAGQgCAEgCACIACAGIABATQAAAHgBACIgEADIgCAAIgDgBg");
	this.shape_7.setTransform(15.725,36.0125);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4}]}).wait(25));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.3,-66.3,110.69999999999999,132.7);


(lib.foxs = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C46600").s().p("AghToIADABIgQgIIAEACQgqgagUhOIgCgIQgOg7AAhIQAAgmAegQQAagOAhALQAigdA1ANQAxAFAyAZIgGgDQBHAZAyA0IADAEQBTBQghBiIADgKQgGAVgJAQIAEgKIgBADQAPgggNgXQgOgbgjAWIgQAKIgEACIgaAHIglAKIgSAEIgCAAIgBAAIgBAAQgMABgNAEIgdAGQgRAEgKADIAFgCQgIACgRACIglAAQgcAAgCAeIAAACQgOgEgNgGgABEQ5IAAABIAAgCgAF4Q9QgegMgJgcIgDgMQgPgLgTgRIgFgGQglgkAcgpQAWgfAggDQgCgJAAgLQAAgLAEgLQAMgjA2gTIAEgBIAMgEIAPgGIgIADQAygXAuAGQAzAGAeApIgBAAIABAAQAFAHAEAIIALATIgIgDQgagGgFA0IgJAeIgTAcQgMARgFAMQgLATAQARIgBAAQgbADgCAcQgBAUANAGIgTAHQgJAEgMADQgfAKgfAAQgeAAgXgKgAB8KPIgVgBIAWAAIAEABIgFAAgAAQJwQgygigNg8IgKgiIgNgxIACAHQgFgTgDgVIgCgUQgfgBgRgWQgOgTACgcQADgcATgUQAUgVAgAAQBFAAAjACIAVABQAtAEAmAKIgOgDIA8AQQAmALAaAWIgFgEIANAMQAQAPAJATQAJAPAFAPQAMAhACAeQgGgEgLgBQgegCAAAdIAAABQgSgFgXAHIABgBIgFACIgCABQgWAIgSAMIgZAOIAEgCQgPAHgXAKIAEgBQgYAIgUAOQggATgQAbIABgCIgBADQgGANAAAMQAAAGACAEIgOgIgACVGYIAIADIgNgHgAG3E7QgIgOgFgSQgGgWgCgaIABAJIgDgQIACAGIgKgjIgNgnQgGgVAAgVQAAgKACgIQgMgSAAgYIAAgBQAAgQAFgMIABgCQAGgLAJgIQAUgOAcADQAcACAUASQAHAGAFAIQAKAEAaAQIgMgGQAdAQAUAbIAGAJQARAcAMAgIABADIADAKQAGATAAASIgCgBQgkgIgiAiQgMAMgGAKIgIAMIgPAPIACgCIgHAGIgNAHIgEABQgMACgHAJIgBAAQgVAAgHASIgEgHgAJtCuIgBgEIAAgBgAh6j1QhDgCg5gPQgwgNgvgYIgUgMQiNhRhKitQhKitAgipQAFABAGAAQAIAAAFgDIAPASQAFAGAEAAQADAAACgDQACgDAAgEQAAgEgGgIIgMgQIABgJQAAgSgIgOIAAABQgDgHgGgHIgBgBQASgvAegnQAIADAHAAQAIAFAKAAQAVAAAFgTIABgBQAJgLAEgJIAEgEIAIAGQACACAEAAQAGAAADgHQADgHgGgEIgIgFIAAgCIASgTIAFgGQAGgKgBgLIAAgCIAQgKIgBAAQAogYAvgSIAMAGQATAMAMACQASADAIgLQAnAUAbAQQAPAIAGgHQAEgFgFgHQgEgGgIgEIhEgkQABgIgDgGQBFgRBRgGQBFgEA8AEQADAHAGAEIADAIQAEAAADgDIAIABQAUACAHgMQA5AJAxATQAFALAPACIATAKIgBAGQgBAGAFADQADADAFgBQADADAFAAQAFAAADgDIACACIAAABQAPAMAMAAIAFAAQAyApAhA9IgBADIgKAmQAEAEAFABQAGAAAEgDIAEgKIAGAGQAUAvALA6QAKAzABAzIgBAAIgigSIgmgbQgXgPgTgBQg+AAgOBAQgCAJACAJQghAFgSAdQgQAaAGAeQghAUgIAnIgdANQgWAKg4AeQgwAagdAMQgyATgYALQgqAUgUAbQCNhJCDg+IAvgVIgBARQABA2AWApIksC1QgKAGgEAJQgGAKAIAFQAHgNAOgMQAIgHAUgLIELigQAJAPAMANQAvA1BIAAIAJAAQgrBBg8A6IgXAWQhmBbhbAAQg7AAgxgngAgvlsIAXAAQASgCAUgEQglgHgoAAQAKAEAGAJgAjTtqQgBAGAGAGQAGAEAHABIAOABQAJAAAFACQAGADAIAIQAIAJAFACQAGADAKABIAzAHIANgqQAEgOgBgHQAAgNgKgGQgDgBgLgBIiZgCQgNAAgHABQgIACgCAEQgDAFACAGQACAGAFADQAIAEAPgBIAFAAQALAAAGADgAENvzQgFAHgDACQgDACgKAEQgLAEgHAJQgIAKACALQACANAOAHQAJAFAQAAIAOgCQAPgGAMgXQAIgNgCgKIgDgKQABgFAEgEIAHgJQAFgHgCgJQgDgKgIgDQgbAMgRAZgAESpRIAFgDIA9AAIgSALIgBABIAEgDIgFADIgYAGgAE/pHIABgBIgEADgAEOpUIADAAIgDABg");
	this.shape.setTransform(161.9667,130.041,0.7614,0.8221);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AitHgQAEgJAKgGIEsi1IBHgrQAcgRATgEIADgBIAIgBIgCABIgFADIh2BGIkLCgQgUALgIAHQgOAMgHANQgIgFAGgKgAiKEZQAYgLAygTQAdgMAwgaQA4geAWgKIAdgNQBOgeA+ALQgDALgXgCQgmgEgtAOIggAMIgvAVQiDA+iNBJQAUgbAqgUgAI1CwQgFgCgIgGIgBgBIgNgKIgQgGIgKgGIgEgDQgHgHAAgQQABgXANgTQAEgFAEgCIAEAAIABgCIAAgBIAMAEQAVAHAUAMQAMAIAEAGQAHALgBASQgBAUgIALQgFAHgIADQgFACgFAAIgGAAgAHQAPIAAAAQAWgdAWgPQAKgHAXgNIAagUQAQgLAMgEQALgDABgEIANACQgDAKgMAGIgWAIQgKAEgPAKQgxAigVAXQgGAHgEACIgGACIgIgCgAiFgMQgKgBgGgDQgFgCgIgJQgIgIgGgDQgFgCgJAAIgOgBQgHgBgGgEQgGgGABgGQgIgEgOABQgPABgIgEQgFgDgCgGQgCgGADgFQACgEAIgCQAHgBANAAICZACQALABADABQAKAGAAANQABAHgEAOIgNAqIgzgHgADlh+QgOgHgCgNQgCgLAIgKQAHgJALgEQAKgEADgCQADgCAFgHQARgZAbgMQAIADADAKQACAJgFAHIgHAJQgEAEgBAFIADAKQACAKgIANQgMAXgPAGIgOACQgQAAgJgFgAnckWIgIgGIgJgGQgLgCgOgIIgYgPIgQgJIgrgSQgYgMAIgOQAJgNAYADQANABAOAKQANAIAIALIACADIAUAPIAAAAIAdAVIAFAAQAIAAAAAIIAAAAIAAACIAIAFQAGAEgDAHQgDAHgGAAQgEAAgCgCgAo1lbIACAAIgLgGIgNgFIgCAAgADcl0QgFABgDgDQgFgDABgGIABgHQABgJAEgJQADgHAJgPQADgLAJgNIAPgWQAGgLAMgFQAOgGgCARQgCAOgRATIgMAOIAAABIgIALIgGAXQgBAFAAAQQAAAEgBACQgDADgFAAQgFAAgDgDg");
	this.shape_1.setTransform(162.8102,62.9826,0.7614,0.8221);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AFURXQg1gKghgbQgWgSgTgfQgMgUgSgnIgSgoIAVAAIAVABIAFAAQAeAIAVAAQAfAAAZgQIgDACQAKgFANgLIAXgTQAVgOALgUQAOgTACgdIABg0QAAgTgNgIQgDgegMghQgFgPgIgPQgKgTgPgPIgNgMIAEAEQgZgWgmgLIg9gQIAOADQgmgJgtgFQAeiDB3h8QAXgXASgMQAPgLAcgMQARgHAJAAQAVABASAiQARAeAJAaQgGAMAAAQIAAABQAAAYAMASQgCAIAAAKQAAAVAGAVIAOAnIAKAjIgCgGIACAQIAAgJQACAaAFAWIABAGQACAnAABMIgDEqIgDAVQgFAjgJAiQg2ATgMAjQg2gBgfgGgADoKoIgGgEIANAHgAGpi9QgGgEgCgGQgCgHAFgLQAOgeAigcQAUgQArgeQAqggAhgsIAKAFIAQAGIANAKIABABIAAADQAAAOgCAHQgDAHgHAIIgEAEIgKAIQgIAJgKAPIgRAZIgFAGIgTATIgEADIgFAEQgKAIgNAIQgWAOgtAUQgOAHgKAAQgHAAgGgDgAnFsVQgHAAgHgDQgOgGgPgRIgOgOQgLgKgTgLQghgPgngjIABAAQhEg4BDgYQA4gTBEANIAHABIgGgBQAUAFAfAQIAkASQAgAPAHAWQAJAHABAKIAAACQACALgHAKIgFAGIgRATIAAAAQAAgIgJAAIgFAAIgdgVIABAAIgVgPIgCgDQgHgKgNgJQgPgKgNgBQgYgDgIANQgJAOAZAMIAqASIAQAJIAYAPQAOAIAMACIAIAGIgDAEQgEAJgJALIgCABQgEATgWAAQgKAAgIgFgAnDtWIADgDIgKgFIgCgBIAIAHIgEgDgAoxumIADACIABgCgAnYt7IgXgLIACAAIANAFIAKAGgAFMuRIgBgBIgCgCQACgCAAgEQAAgQABgFIAGgXIAHgLIABgBIALgOQASgTACgOQACgRgOAGQgNAFgGALIgOAWQgJANgDALQgJAPgDAHQgEAKgCAJIgTgKQgOgCgFgLQgDgHABgJQABgZAXgFIANgXQAFgIAIgJIgCADIAKgQIABgBIAAAAQAHgLALgMIAVgVIgEAFQAlgpAQAjQAOAggOAoIgIAhQgJBZgdAGIgEAAQgMAAgPgMg");
	this.shape_2.setTransform(155.6875,107.6709,0.7614,0.8221);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#CC6600").s().p("ArcWHQgMgpgpgYIACABQgUgNgegLQAwgUgMgbQgKgWgxgWQAcgVAMgVQAPgagOgVQgIgMgWgEQgNgCgdABIgBAAQAFgEAEgGIACgCIAPgPQAogogegVQgUgPg0gFQADgJAJgRIgBABQANgVAPgTIAJgJIAAAAIAJgIQAGgGADgEQAGgKgBgMQgCgOgKgFQgPgIgVAHQgFgRgeABQgNABgMADQC2hJDJgCQDTgCDABMQAfAMAKARIAAAAQgYgfgSghQgyhcgSiAQgNhYAAiTQAAh7ALhIQARhrAuhJQAkg3BThIQBjhXBXgxQAvAYAwANQA5APBCACQAxAnA7AAQBcAABmhbQBRA+A8BqQAqBLAWBMIACAFIgBACQgJgagRgeQgSghgVgBQgJAAgRAHQgcALgPALQgSAMgXAXQh3B8geCDIgVgBQgigChHAAQgfAAgVAVQgSAUgDAcQgDAcAPATQAQAWAfABIACAUQADAVAFATIgCgHIANAxIAKAiQAOA8AyAiIAPAIQACAIAGAFQAHAGAIACQAFABAHAAIARAAIASAoQASAnAMAUQATAfAWASQAhAbA1AKQAfAGA2ABQgEALAAALQAAALACAJQghADgVAfQgcApAkAkIAGAGIgVAXIgJALQgyg0hIgZIAGADQgygYgwgGQg1gNgkAdQgggLgbAOQgdAQAAAmQAABIAOA7IACAIIgGgBQg+gEgwgOQg5gShNgtIgygfQAAAHgEAHQgQAegfAdQgUAUgmAcQjoCpj7A6QhsAZhrADQAZgKgJgfgAtrWqIAHAAIALAAIAMADIgegDgAITRnIAAgBIABACgAueQHIABAAIAAABgAvaN3IgDABIgUAKIgFABIAcgMgAN2MBIADgVQgDAkgFAbIgGAaIgDABQAJgiAFgjgAGgk+QgHgIgJgFQAoAAAlAHQgVAFgSABgAKBnBQgMgNgJgPIB2hGIAWAPIAXgGIAFgDIgEADIABgBIASgLIg8AAIABgBIgIABIgCAAIAAABQgUAEgcARIhHArQgWgpgBg2IABgRIAggMQAugOAmAEQAXACACgLQg+gLhNAeQAIgnAggUQgFgeAQgaQARgdAhgFQgBgJACgJQANhAA+AAQATABAXAPIAmAbIAiASIACAAIADACQASAHAKALIATAFIABAAIAHACQApAOAUAaIAAABIACACIADAFIgCgDIAFAJIgNgEIABABIgCACIgDAAQgFACgDAFQgNATgBAXQAAAQAGAHIAFAEQghAsgqAgQgrAegUAQQgiAcgOAeQgFALACAHQACAGAGAEQAGADAHAAQAKAAAOgHQAtgUAWgOQANgIAKgIQgMAMgOAHIAAAAIgUALQgQANgRAIIAHgFQgdATgeAEIANgEQgYAHgXABIgJAAQhHAAgvg1gAMPoZIgDACIAEgDgAOqnZIAEgDIgGAFgAPGn1IARgZQAKgPAIgJIAKgIQgOAagZAZIgLAMIAFgGgAh0tNIgOgSIAFgDQAFgEACgHIAMAQQAGAIAAAEQABAEgCADQgCADgEAAQgDAAgGgGgAilvHIgdgWQgOgOgSgXIgvhJQgMgbgHgMIACADIgfg6QgSgigNgVIgBgCQgHgMgMgRQAbgCAQgFIgIADQANgEASgCQAogBAuADQAeACA4AFIAaAHQARAHAQAEQAfAJAKACQAfAKAkASIAHAEQAPALALAEIARAJIAFADIARAIQAPAJAJADIACABQgvASgoAYIABAAIgQAKQgBgKgJgHQgHgWgfgPIgkgSQgfgQgUgFIAGABIgHgBQhEgNg4ATQhDAYBEA4IgBAAQAnAjAhAPQATALALAKIAOAOQAPARAOAGQgeAngSAvQgMgRgTgSgAM6vTQgGgBgEgEIALgmIABgDQghg9gzgpQAdgGAJhZIAIghQAOgogOggQgQgjglApIAEgFIgVAVQgLAMgHALIAAAAIgBABIgKAQIACgDQgIAJgFAIIgNAXQgXAFgBAZQgBAJADAHQgygTg4gJQADgGAAgKIAAgFIADgIQAIgNASgUQAkgkAPgKIAYgSQAIgEAXgRQAOgJAbgTIgCABIAcgUIAQgKIAigVIAkgUQgDArAJAiIADAHIgBgCIALAdIAJAnIAEAZIADBlQABA7gEArIgFAMQgGAKgDAJIgGAIIgCACQgPAPAJAUIAGAJIgEAKQgEADgFAAIgBAAgAhLw9IAEADIgIgHIACABIAKAFIgDADgAEKxjQgagQgogUQAEgGACgJIABgGIBEAkQAIAEAEAGQAFAHgFAFQgCAEgFAAQgFAAgJgFgAi0yIIAEAAIgBACgAHty2QAFAEAGABQgDADgEAAIgEgIgAmh03IAEAAIgSADQAFgDAJAAg");
	this.shape_3.setTransform(126.6817,126.2549,0.7614,0.8221);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#160000").s().p("AoAXaQggAAgjgHIgLgDIgLAAIgIAAIg1AAIgVgBIgJABIgQAAQgbAAgPgCQgVgDgSgKIgKgEIACAAIgigIQgggGgQgFQgVgEgYgGIgugLIgigJIAIABQgagGgagNIAFADIgVgKQgRgIgngNQghgKgTgJIgFgCIgTgKIACABIgbgNIg6gcIg2gcIABAAIgegOIgOgFQgcgJALgcQACgIAFgFQACgIAKgIQAUgRAjgEQAQgHAMgCQAJgBAHADIA0gQIA1gUIAbgKQAlgOAwgZIBRgtIgBABIAVgKIAVgLIgCABQAdgRAcgJIAbgLIgEABIAegKIAIgEQARgKAQgGIAEgCIAAABIABgBIgBAAIAkgIIAFgBIAUgKIACgBQAMgHANgEQAMgDANgBQAegBAGARQAUgHAQAIQAKAFABAOQABAMgFAKQgDAEgGAGIgJAIIAAAAIgJAJQgQATgMAVIABgBQgKARgCAJQA0AFAUAPQAdAVgoAoIgOAPIgCACQgEAGgFAEIABAAQAdgBAMACQAXAEAIAMQAOAVgPAaQgMAVgcAVQAxAWAKAWQAMAbgwAUQAeALATANIgBgBQApAYAMApQAIAfgYAKQgMAEgTAAgAqTQuIAAgBIAAAAgANjV6IgwgOIgDAAQgPAAgHgLQgWABgXAAQgcAAACgcIAAgCQACgeAeAAIAkAAQARgCAIgCIgFACQAKgDARgEIAdgGQANgEAMgBIABAAIABAAIACAAIASgEIAlgKIAagHIAEgCIARgKQAigWAOAbQANAXgPAgIABgDIgEAKQgPAdgwAeQgcASgjAAQgVAAgbgHgATtSDQgNgGACgUQABgcAbgDIABAAQgPgRAKgTQAFgMAMgRIATgcIAJgeQAFg0AbAGIAIADQATAJAMAlIAAAAIABADIACAEIgBAAQANApgUApIgEAHQgJARgKALIgEAEIgOAQQgiAkgiAAQgJAAgGgDgANbLjIgDgBIgXAAIgUAAIgRAAQgHAAgFgBQgIgCgHgGQgGgFgDgIQgBgEAAgGQgBgMAGgNIACgDIgBACQAPgbAhgTQATgOAYgIIgEABQAYgKAOgHIgEACIAagOQARgMAWgIIADgBIAEgCIgBABQAXgHATAFIAAgBQAAgdAeACQAKABAHAEQANAIgBATIAAA0QgCAdgOATQgLAUgVAOIgXATQgNALgKAFIADgCQgZAQgfAAQgWAAgegIgASxHFIgKgFQgZgEAEgcIADgKQAHgSAVAAIABAAQAHgJAMgCIAFgBIAMgHIAHgGIgBACIAOgPIAIgMQAGgKAMgMQAjgiAjAIIACABQAiAJgZAwIADgGQgOAbgIAKIgIAJIADgCIgMAOIAAABQgHAKgIAIQgpAtgjAAQgSAAgTgLgABvs3QgFgCgFgEQgLgIgBgNIgCgDIgLgSIAAgBQgIgFgJgJQg1gqgVgmIAAABIgMgWQgLgOgKgQQgMgSgOgeQgNgUgQggIgbg1IgRgbQgHgKgHgMQgEgFgFgFIgMgKIgCgCQgngoA7gNIARgDQAWgDAggBIABAAIADgBIgBABIABgBIAAAAQBcgcCjAkQANADAYAJIAjAKQAvAMAyAbIByA8IAFACIAAAAQANAFAEAKQADAGgBAIIgBAGQgBAJgEAGQgIALgRgDQgNgCgTgMIgMgGIgCgBQgKgDgOgJIgRgIIgFgDIgRgJQgLgEgPgLIgHgEQglgSgggKQgJgCgfgJQgQgEgSgHIgagHQg3gFgegCQgugDgnABQgTACgMAEIAIgDQgRAFgaACQALAQAIANIAAACQAOAVASAiIAfA6IgCgDQAHAMAMAbIAuBJQASAXAOAOIAdAWQATASALARIABABQAGAHADAHIAAgBQAIAOAAASIgBAJQgCAGgFAFIgFADQgGADgIAAQgGAAgFgBgACm0OIAAAAIgBAAgARYu0IgGgGIgFgJQgKgUAQgPIACgCIAGgIQADgJAGgKIAFgMQAEgrgBg7IgDhlIgEgZIgJgnIgMgdIACACIgDgHQgJgiADgrIgkAUIgiAVIgQAKIgcAUIACgBQgbATgOAJQgXARgIAEIgZASQgOAKgkAkQgSAUgIANIgDAIIAAAFQAAAJgEAHQgHAMgUgCIgIgBQgGgCgEgDQgGgEgDgHQgDgGABgIQAAgjAmgsQAhglAngXIAjgYIAhgWQANgLAPgJQAbgVAJgFIAZgOQAOgKAdgPIAQgKIARgLQAhgTAVAIQAXAKgJApIACgGQgEATAAAZIAAAsIAGAQQALAaADAbIgBgDQATA8ABBaQABBkgYAzIgBACQgNAbgOAOQgJAIgKAAQgIAAgHgEg");
	this.shape_4.setTransform(106.3821,123.1379,0.7614,0.8221);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.foxs, new cjs.Rectangle(0,0,212.8,246.3), null);


(lib.clouds = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A6sPxQgmgxgOhQQgNhTAoARQALAFgBgWQgBgZAHgYQADgJAFgKIAHgOQAGgIAIAGQAGAFADAMQACAMADgCQADgBACgQQAEg0ATgOQAJgHAHASQAGAPAEAXQACAPAEgBQAEgCABgSQABgVAFgQQAGgSAJgDQAHgCAHAQQAIATgBAdQgBALADAEQADAEADgFQAQgdAMAZQALAYgFAhQgBAJACAEQABAFAEACQAQAHAFAHQAIAMACAjQACAagIAWQgIAUgIgCQgEgBgCADQgBAEgBAQQgBAmgNAJQgPAKgSgcQgFgGgCACQgDACgEAMQgKAmgRgFQgQgFgQgpQgFgMgDACQgDACgEAQQgLAzgQAGIgEABQgLAAgNgXgAoqMrQhPgLhIgjQhFghgkgoQglgqARggQASgiBSgKQAvgGgMgdQgOgiAVgmQALgTAPgQIAEgEIAHgLIAMgMQAVgSAfAAQAdAAAOAOQAOANAMgFQAMgGAAgXQAAhMBCgnQAhgTAmARQAdAMAYAdQAOASAOgGQAPgHgDgZQgEgeAOgbQARggAlgNQAcgLAiAOQAoARAEApQACAPANADQAMACAKgKQA2g5A4AWQAYAJANAUQANAUgCAWQgCAMAIAFQAHAFAPgCQBFgIAVAEQAkAIAXAuQAQAhgZAnQgXAjgfAGQgUAEgEAFQgGAIAFAWQALA0gzAcQg2AchVgRQgTgEgKAGQgKAGgJAUQgcA/hFALQhBALhRgmQgZgLgMAGQgLAFgJAbQgaBSg7AZQgaALgeAAQgeAAgigLgA6CGzQhXgQgughQgxghASgkQAUgoBjgeQA4gSgRgaQgTgfAWgtQAMgWAQgTIANgSQAGgHAIgIQAXgYAngHQAjgHASAKIACABIAagJQAPANAPgGQAQgHACgWQAHhNBXgoQArgVAuARQAjAMAaAdQAQARATgGQASgGgBgaQgBgfAVgbQAYghAwgOQAjgLApANQAvAQACAqQAAAQAQACQAPACANgKQBKg7BFAVQAcAJAOATQAPAVgGAWQgDANAJAEQAJAFASgCQBWgKAbAFQArAHAYAuQARAhgjAnQghAlgnAGQgZAEgGAGQgIAIAEAWQAIA1hDAdQhGAehpgRQgXgDgNAGQgNAGgOAVQgpBAhXANQhTAMhgglQgegLgQAGQgPAGgNAbQgoBShKAbIAwgQQg9AlhYgGQggADgfAAQhAAAg+gMgAIYBQQhpgfhXg0QhSgygigxQgjgyAjgaQAmgcB1AMQAkAEAPgJQAMgGgCgNQgGgkArggQAWgRAagKIAHgDIAOgIIAVgJQAkgMArAIQAnAIAPARQANAQASgCQAUgCAIgXQAchJBqgUQA1gKAuAbQAkAUAVAhQANAVAWgCQAWgCAFgZQAHgeAdgWQAkgbA4gDQAqgDApAWQAxAbgJApQgEAPARAGQAQAFARgHQBggpBHAkQAcAPALAXQALAXgMAUQgGALAIAHQAIAHAWACQBiAKAbAKQAuARAOAyQALAlgxAeQgtAdgtgDQgdgBgIAEQgKAFgCAXQgEA0hSANQhUAOhwgnQgZgJgQADQgPADgVARQg+A1hjgHQhegGhhg6QgdgSgTADQgSACgWAXQhCBIhbAJIgbACQhCAAhIghgA2KltQgxgwgRhRQgRhTAzARQAOAFgBgWQgCgZAKgXQADgLAHgIIABgCIABgCIAHgKQAIgJAJAGQAIAGAEAMQADALADgBQAEgCACgQQAGgzAXgPQAMgHAKATQAHAOAFAYQADAOAEgBQAFgBABgSQACgVAGgQQAIgTAMgCQAJgCAJAQQAKASgCAdQAAALADAEQAEAEADgFQAVgdAPAaQAOAYgGAhQgBAHACAGQABAFAFABQAVAHAGAHQAKAMADAkQACAagKAVQgKAUgKgBQgGgBgBADQgDAEAAAQQgBAlgSAKQgSAKgYgdQgFgGgEACQgDADgEAMQgOAmgVgFQgUgFgVgpQgGgNgFACQgEACgEAQQgPAzgTAHIgGABQgOAAgQgYgAklmKQhGgfg7g1Qg4gygXgxQgXgyAXgaQAagcBPAMQAtAHgEgfQgEgkAdggQANgQAUgLIAEgDIADgDIAHgFIAOgJQAYgMAdAIQAbAIAKARQAJAQAMgCQAOgCAFgXQAThJBHgUQAkgKAfAbQAYAUAOAhQAJAVAPgCQAPgCADgZQAFgeAUgWQAYgbAmgDQAcgDAcAWQAhAbgGApQgDAPAMAGQAKAFAMgHQBBgpAwAkQATAPAIAXQAHAXgIAUQgFALAGAHQAFAHAPACQBDAKASAKQAfARAKAyQAHAlghAeQgfAdgegDQgTgBgGAEQgHAFgBAXQgDA1g3ANQg5AOhMgnQgRgJgLADQgKADgOARQgqA1hDgHQg/gGhBg6QgUgSgNADQgMACgPAXQgtBIg9AJIgSACQgtAAgxghgAQCqZQg/gwgWhRQgKgkAKgSQAKgUAhAIQASAFgCgWQgBgZAMgXQAFgLAIgIIAMgOQAKgJAMAGQALAGADAMQAEALAFgBQAGgCACgQQAIg0AdgOQAOgHANATQAKAOAGAYQAEAOAGgBQAGgBABgSQACgVAIgQQAKgTAQgCQALgCAMAQQANATgCAcQgBALAEAEQAFAEAEgFQAbgdAUAaQASAYgIAhQgBAJACAEQACAFAGABQAbAHAIAHQANAMAEAkQADAagOAVQgNAUgMgBQgIgBgCADQgDADgBARQgBAlgXAKQgXAJgfgcQgHgGgEACQgEADgGAMQgRAmgbgFQgagFgbgpQgJgNgFACQgFACgGAQQgSAzgaAHIgHABQgSAAgUgYg");
	this.shape.setTransform(183.8356,83.7524);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.clouds, new cjs.Rectangle(0.3,-19.4,367.2,206.4), null);


(lib.chair2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,204,255,0.988)").s().p("AibN6QkugGjcgtQhCgNgwgOQgtgOgegOQhAggAAgkQAAg2CLgqQAwgPBCgNQD8gzFmAAQE4AADoAnQAfmOAdmhIAHhaQAdlSA0hQIAAAAQAfgvAagjQAXggAUgVQAOgRAXAKIAAA8QABCxAHCJQALDBAOAAQAOAAAklEIAIhFQAOApAJAgQAcByAOAMQANB6AAClQAAGhg+EoQgiCihuCIQBAgpgcAVQgLAHgPAIIgKAFIAAAAIrBBog");
	this.shape.setTransform(93.1,186.9932);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0.988)").s().p("ACDKmQgOgMgdhyQgIgggOgpQAIg8AJg2QAWiJAehqIAEDzIADCBQAGC5gOAAIgDgBgAhGCeQiAkKBhktQBikuBLAlQBGAigCCuQiTAugJCpQgJDBAAEQIAAAoQgVgtgYgzg");
	this.shape_1.setTransform(171.8197,67.8929);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.988)").s().p("ApDVsImapIIACABQAeAOAsAOQAxAOBBANQDdAtEtAGICwAAILAhoIAAAAIllIDQjkFLjZAAQjCAAi6kJgAKJnqQgHiJgCixIAAg8IgBgzIAAgoQAAkRAKjBQAJipCUguQAUgHAYgEQC/ghhGCuQhHCvhGDBQgQAqgOAxQgeBqgWCJQgJA2gHA8IgJBFQgkFEgOAAQgOAAgKjBg");
	this.shape_2.setTransform(105.2637,184.8511);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.chair2, new cjs.Rectangle(0,0,204.3,350.2), null);


(lib.chair1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,204,255,0.988)").s().p("AgSN6IrChoQhuiIgiiiQg+koAAmhQAAilANh6QAOgMAchyQAJggAOgpIAIBFQAlFEAOAAQANAAAKjBQAHiJACixIAAg8QAXgKAOARQAUAVAXAgQAaAjAfAvIAAAAQA0BQAdFSIAHBaQAdGhAfGOQDpgnE3AAQFmAAD8AzQBCANAwAPQCLAqAAA2QAAAkhBAgQgdAOgtAOQgwAOhCANQjcAtkuAGgAreMNQgPgIgLgHQgdgVBBApIAAAAIgKgFgArUMSIAAAAg");
	this.shape.setTransform(111.15,186.9932);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0.988)").s().p("AiNHuIADiBIAEjzQAeBqAWCJQAJA2AIA8QgOApgIAgQgdBygOAMIgDABQgOAAAGi5gAAaDWQAAkQgJjBQgJipiTguQgCiuBGgiQBLglBiEuQBhEtiAEKQgYAzgVAtIAAgog");
	this.shape_1.setTransform(32.4303,67.8929);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0.988)").s().p("Aj1UqIlloDIAAAAILABoICwAAQEtgGDdgtQBBgNAxgOQAsgOAegOIACgBImaJIQi6EJjCAAQjZAAjklLgArSptIgJhFQgHg8gJg2QgWiJgehqQgOgxgQgqQhGjBhHivQhGiuC/AhQAYAEAUAHQCUAuAJCpQAKDBAAERIAAAoIgBAzIAAA8QgCCxgHCJQgKDBgOAAQgOAAgklEg");
	this.shape_2.setTransform(98.9863,184.8511);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.chair1, new cjs.Rectangle(0,0,204.3,350.2), null);


(lib.carrot = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("rgba(255,153,51,0.757)").s().p("AsuSmQhcglgogeQgrgfgRglQgMgZAAgcQAAgNAEgLQAFgPAMgJIAJgHQAQgIAVABQAbACAUAQQAWATADAdIAAgKIgEgMIgEgGIADAFIgBgEIADAFQAOAVASARQAHAHAKAFQAMAFAWAHIAhAMQA2AWgMA6QgEASgHAMQgRAbgjAAQgOAAgNgFgAhmQ/QgzgEgDg2QgDg5AxgTIABgBIASgEIgHABIgKADIgBAAIgEACIAIgEQAYgPAygaQAXgSAbgeIgEAFIAbgaIADgDQAUgYAegCQAbgCAXARQARAMAHAQIAEAMQAGAbgUAZQgHAJgOANIgWAVIAHgHQgeAfgpAdIhTA2IgEACIgHAEIAGgDQgbAQgfAAIgIAAgAsWJfIAEADQg/gigkggQg6g0AAg3QAAgRAFgMQAMgfAqgCQA6gDASAzIALAMQAlAfAsAYIAGADQAwAagVAxQgLAXgRAMQgSANgbAAQgSAAgQgJgAJwhVQgpgGhCABQhIADgjAAQggAAgRgVQgPgUACgcIACgMQAEgUAPgQQAVgWAgAAQA1AABjADQBpACAvAAIBPAAQAugHArgLIAYgKIADgCQAdgOAaALQATAIALASIAFAKQAMAZgGAaQgIAcgcAPQgEACgPAFQhzAoh7AAQgyAAgygIgAoEidIgagaIgagaIAFAFQgogmgegtIgSgbQgfgygOgkQgRguAAgzQAAggAWgRIAJgGQARgJAWACQAcADAUASQAVAVAAAgIAAAPIADANQAKAZAOAXIAZAmQAaAmAgAfIgNgMIAwAwQAgAjgUAuQgRAnghAFIgJAAQgVAAgTgQgAJlrCQhFgGgiAAQggAAgRgVQgPgUACgcQADgcASgUQAVgWAgAAQAmAABPAFQBMAGAogBQAUgCAPgEIANgEIAVgKQAOgUAagDQAXgEAWAMIABAAQAvAZgJAuIgDANQgGARgQAOQgKAJgTALIgDACQgYANgeAKIgJACQgwANg/AAQgjAAhFgFgAkxthIgggcIANAMQgMgKgNgNQgUgRgJgJIACACQgTgTgQgXQgTgegKgkIAFAOQgMgoAHgyIACgMIAAgIQAAggAWgRQAUgPAcACQAcADAUASQAVAVAAAgQAAALgEAQQgCALABAOIACAIIAIAPIAUAWIAiAeIgBAAIARAOQAmAigSAxQgIAUgMALQgQARgZAAQgVAAgTgRgAmdvNIACADIACADg");
	this.shape.setTransform(-32.6608,56.0321);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,153,0,0.757)").s().p("AnJTBQgPgUADgcQACgcASgUQAVgWAgAAIABAAIAdgIQAOgGAVgHIgGACQATgKBCgfQA1gZAfgTIAggZIgHAHIAMgLIAHAAQAfAAAbgQIgGADIAIgEIADgCIBTg2QApgdAfgfIgHAHIAVgVQAOgNAHgJQAVgZgHgbIgDgMQAQACAQAMQAYAQAGAaQAEAMgCANIAAADIhfBtQgaAcg7AwIgsAmQhZBJg7AuQg0AbgzASIgXAIIg6ATIAGgCQgdAJghAAQggAAgRgVgAmUROIAHgCIAAAAgAr0QbIgJgEQAIgMADgSQANg6g2gWIgigMQgWgHgMgFQgKgFgHgHQgRgRgPgVIgCgFIABAEIgDgFIADAGIAEAMIAAAKQgCgdgXgTQgUgQgbgCQgVgBgQAIQgQgagMgbIgEgJIAEgaIACgaIAAgJIAAgBIAAAAIACgYIAEgUIAAgBIAAgBIAAgDIAAgPIAAgJIAAgBIACgRIABgHIAGgYIAAgEIABgKIABgIIgBgDIgBgLIADAAIAKAAQAcADAUASQAWAVAAAgIAAAOQABAMAEAPQAUA2AdA0IAaAoQALARAjAkQAcAXAgASQANAGAnAPQA3AVgNA6QgMA5g0AAQgNAAgNgFgAr5JyQhKgggwgqQhIg+geg4IgQgTIADgPIABgGQAIguABggIAAgaIADgBQAIgCAJAAQgEAMgBARQABA3A5A0QAkAgA/AiIgEgDQAQAJATAAQAaAAATgNIAcAMQA1AXgMA5QgMA5gzAAQgOAAgNgFgAASJUQgngDgzgLQgIgBgcAAQgfAAgRgVQgPgUACgcQADgcASgUQAVgWAgAAQAgAAAuAMIArAGIAsAHIgFgBQA6AMBYgCICTgFIAEgBQAegMAbAOQAYALAMAaQAIAQAAAQIgCALIgGAKIgFAIIgFAHQgIAHgDAHIgMAFIgHADIAAAAQhBAWhqAAQh5AAhpgZgAGjF/Ig4gCQghAAgRgVQgOgUACgcQACgcATgUQAVgWAgAAICfAAIAEgDQARgUAUgJQAcgOAaAMQAYAKAMAZQAEAIACAIIABAEIgYAbIgCACQgGAGgHAMIgLAPIgXAjIgEAGIgQAGIgMAEQgkAJg1AAIg7gCgAlEgGIgGgCQhAgPgpgeQgtgXgggTQhag1hMiBIgog2QgWgggOgYIAGAIQgZgpgOgrQgQgugHgwIgBgQQATgwAGg2IAEgCQARgIAUACQATABAOAJIgJAGQgVARAAAgQgBAzASAuQANAkAgAyIARAbQAfAsAnAnIgFgFIAaAaIAaAaQATAQAWAAIAJAAIAKALQAcAaAWANIgHgDIArAbIA2AbQAYAMAQAEQAVAEAKAEQA4ASgOA6QgFAZgSAQQgUASgZAAQgKAAgNgEgAEFkjIhGACQggAAgRgWQgPgTADgdQACgcATgUQAVgVAfAAIBaAAQAwABAlAIIgKgCQBIAPBugCQA/gBB6gFIAPgDIgMADIABAAQAigKAjgDIgDAAIAOgCQAUgHAQgDQAegMASgKIAfgXQARgNAOgJQAbgQAaAKQAUAIALAUIACADIAAASIgDARIgBADIgBALQgBARACAQIgJAJQgGAGgHAFIgFACQgVAPgWANQgMgSgTgIQgagLgdAOIgCACIgZAKQgqALgvAHIhPAAQgvAAhpgCQhjgDg1AAQgfAAgVAWQgPAPgFAVQgYgDgjABgAlQtnQgUgKgNgIIgRgJIgDgCIgBgBQgbgPgUgSIgHgHQgVgTgKgKQgTgSgJgTIgCgEQgTgVgKgaQgNgVgGgbQgOgbgCgWQgDggATgXQARgUAdgFQAUgFARAHQgHAyAMAoIgEgOQAKAkASAeIgCgDIAEAGIgCgDQAQAXAUATIgCgCQAIAJAUARQANANAMAKIgNgMIAgAcQAUARAUAAQAZAAARgRIAAABQAgAAARAWQAPATgCAdQgDAcgTATQgUAWggAAQgaAAgtgZg");
	this.shape_1.setTransform(-29.7,68.1455);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(0,153,0,0.757)").s().p("AoQHFQgTgJgKgQIAEAJIhOhZQgrg0gagtIADAFQgUgfgLghIACAFQg2iTgDiCIgCgJIACAEQgHgcAOgZQAOgWAZgLQAZgKAWAIQAZAIALAdQAHATACAZIACArQAFBEAUBCIAXBCQAFAPAJAPIAAgCIAXAnQATAZA7A+QAyA7AAAkQAAAegTARQgRAPgaAAQgTAAgRgJgAo4GVIACAFQgCgHgBgHgAK1DVIgcgMIADAAIgBAAQgcgJgTgQIAAABIgBgBIgYgUIAKAJIgfgbQgngngFg4QgFg0Aag1IgBABQAFgOAOgYQAHgOAOgQIAOgTIAJgMIAMgVQAFgMAKgRIAEgKQABgOgBgbIgDgVQgIgVgPgaQgpgXAPg2QAPg3A4AAQAhAAAbAnIADADQAvBFAJBLQAJBTgpBGIgOAZQgQAcgNAPIAEgEIgQATIAFgFQgFAFgEAHIACgEIABgBIACgFIgDAGIgWAoIAAABIACgDIgCAEQgCAOAAARIAGAFIAXAUIgIgHIARANIAAAAQANAEAKAFIgCgBIAOAGQA3AVgNA6QgNA5g0AAQgNAAgNgFgAKdDKIAJABIgKgCgAmyCxIgZgYIAJAJQgPgPgJgNIABACIgQgZQgNgOgLgXQgig2gGgvIABACQgHgcAPgYQANgXAZgKQAZgLAXAIQAYAJALAdQAFAPAFAdQAGAPANAUIAhAyIAGAGIgEgEIAAABIAOAMQAYAHALAWQALAVgFAaQgMA9g9AAQgaAAgfgdgAlnA4IAAAAIgJgIgAI1CCIAJAIIAEAFg");
	this.shape_2.setTransform(30.0353,-131.475);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#005005").s().p("AA4MSQiYgGhLgqIgvgYIgzgWQgfgNgTgJIAAAAIAMAGIgQgHQgugJgmgTIgbgOIgJgDQghgNgIgdIgCAAQgiAAgsgeQgZgRghggIgRgPIADACIgIgHIgdgcIhAg8IALAKQgagZgbgoQgQgUgOgWIABABQgxhFgZhLIABAFQgMgkgGgYIgFgNIgKghQghhigDhqQgEhkAXhhIABgGQAMg1AOgrQAWhHAbgtQA4hhBug+QBxhACSAjQCOAiBPBmQAkgzAqggQAxgkA+gPIgCABQEBhQDVBkQDgBqBBEDQATBPgcBgQgZBUg5BRQBGAVBBAhQA+AhAbAdQBEBHAMBzQALBrgrBWIgEAIQgVAjglAgQgjAdg2AgQh7BMieAzQhBAXhoAPQhtAPhpAAIgvAAgApwF0QARAIAUAAQAaAAARgPQATgRAAgeQAAgkgzg6Qg7g/gSgZIgYgmIABABQgJgPgGgPIgXhBQgThCgGhEIgBgsQgDgYgHgTQgKgdgZgJQgXgIgZALQgZAKgNAXQgPAYAHAdIgBgFIACAKQACCDA2CRIgBgFQALAhATAgIgDgFQAbAtArAzIBNBZIgEgIQALAQASAJgAJWCEQANAFAMAAQA1AAANg6QANg6g3gUIgOgFIABAAQgJgEgNgEIgBgBIgQgNIAHAIIgXgUIgFgFQAAgRACgOIABgFIgBAEIAAgBIAWgqIADgGIgDAGIAAAAIgCAFQAEgHAFgFIgFAFIAPgTIgDADQAMgOAQgdIAPgZQAphFgKhUQgIhLgwhEIgCgEQgcgmghAAQg3AAgPA3QgPA2AoAXQAPAZAJAVIACAVQABAcgBANIgDAKQgLARgFAMIgLAWIgJAMIgOASQgPAQgGAPQgPAXgFAPIABgBQgZA0AEA1QAFA4AnAmIAfAbIgKgJIAZAVIABAAIgBAAQAUAQAbAIIACABIgDgBgAoRBgQAfAdAaAAQA8AAAMg+QAFgZgKgVQgLgWgZgGIgNgNIAAAAIADADIgFgGIghgyQgNgVgGgOQgFgegGgPQgKgdgZgIQgWgIgZAKQgZALgOAWQgOAZAGAcIgBgDQAHAwAhA3QALAVANAPIARAZIgBgCQAJANAPAOIgJgIIAZAYgAHjA9IgFgFIgIgHgAqYFEIAAgKQAAAHADAIgAI+B4IgCgBIAKADgAnQghIAJAIIAAABg");
	this.shape_3.setTransform(39.5908,-123.3278);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF6600").s().p("AstVRQhIgbgng2IgHgKQgshCgOg3IgNgmQgYg3gLhKQARAlArAfQAoAdBcAlQANAGAOAAQAjAAARgbIAJAEQANAFANAAQA0AAAMg6QANg6g3gVQgngOgOgHQgfgSgcgXQgjgjgMgRIgagoQgdg0gTg3QgEgPgCgMIAAgOQAAgfgVgVQgUgTgcgCIgKgBIAKg0IgDAMIAOhPIAAgCIAEgIIAQAUQAeA3BIA+QAwAqBJAgQAOAGAOAAQAzAAAMg5QAMg6g2gWIgbgMQAQgMALgXQAVgygwgZIgGgEQgsgYglgfIgLgLQgSgzg6ADQgqACgMAfQgJAAgIACQAEgkAFgVIgDAKQAFgXAHg9QAGgwAGgfIgCAJIAShRIACgLQAIglAOg0IATheIgDALQAEgXARhFQANg/AJgkIAVhnIATg9IAGgaQAGAwAQAtQAPAsAYApIgFgIQAOAYAWAfIAnA2QBNCCBaA1QAgATAsAXQAqAdBAAOIAGACQANAEAKAAQAZAAATgRQASgRAGgXQAOg7g5gSQgKgDgUgEQgQgFgZgLIg1gbIgrgcIAGAEQgVgNgcgbIgLgLQAigEAQgoQAUgugggiIgwgxIANAMQgggegagmIgZgmQgOgYgKgZIgDgNIAAgPQAAgfgVgVQgUgTgcgCQgWgCgRAIQgOgIgTgCQgVgCgQAJIAEgSIAAgBIABgDIAAgDIAJgeIAMgkIAVhMQAFgYAQg+QAQhHAohPIgCADIAdg+IgGAKQAUgqAZgdIgFAFIAHgJQAagxAwgeQAngcAlgJIApgRIgIADQATgKAYgHIAsgLQAkgPAegFIA2gTQBZghB5ABIAmACIAIAHIgDgCIAQAPQAiAgAYARQAsAeAiAAIACAAQAJAdAhANIAIADIAcAOQAlATAuAJIARAHIgNgGIABAAQASAJAgANIAyAWIAvAYQBMAqCZAGQAYAPAbAZQAqAkAYAkIgKgPIATAaIAFAIIgBgBQgWgLgXADQgaAEgOAUIgVAJIgNAEQgPAEgUADQgoAAhMgFQhPgFgmAAQggAAgVAVQgSAUgDAcQgCAdAPATQARAWAgAAQAiAABFAFQBFAGAjAAQA/AAAwgNIAJgDQAegJAYgNIADgCQAUgMAJgIQAQgOAGgRIADgOQAQAdAGAZIATA3IgCgEIAGAPQAKAZAGAYIAHAOQANAXAKAeIAQA4QAZBLgBBMQgMgUgTgJQgagKgbARQgOAIgSANIgeAXQgSAKgeAMQgQAEgUAGIgOACIADAAQgjAEgiAKIgBAAIALgEIgOAEQh6AEg/ABQhuAChIgOIAKACQglgIgxgBIhZgBQggAAgVAWQgSAUgDAcQgCAcAPAUQARAVAgAAIBGgBQAjgBAYADIgCALQgCAdAPATQARAWAgAAQAjAABIgDQBCgCApAHQAyAHAyAAQB7AABzgoQAPgEAEgDQAcgOAIgdQAGgZgMgaIgFgJQAWgNAWgPIAEgDQAIgEAGgGQgHAigNAiQgWA7gtBRQg3BdgbAvQgQAjgiAzIg2BUIADgHQgIAPgOAVIgXAjIAFgJQgQAbgXAaIACgCIgUAYQgCgIgEgIQgNgZgXgKQgagLgcANQgUAKgSAUIgDADIigAAQgfAAgVAVQgTAUgCAcQgDAdAPATQARAWAgAAIA4ACIA8ACQA1AAAkgKIAMgDIgzBKQgkA4gdAmQAAgPgIgQQgMgagZgMQgagNgeALIgEABIiTAFQhZACg5gLIAFABIgsgHIgrgHQgugLghAAQgfAAgVAVQgTAUgCAcQgDAdAPATQARAWAgAAQAcAAAIABQAzALAnADQBpAYB5AAQBqAABBgWIAAAAIghAjIALgMIgWAXQgbAhgdAeIgOAQIACgCQgRASggAcIgWAUQgGADgHAIIgBACIgNAMIgBACQABgNgDgNQgHgZgXgRQgQgLgQgCQgIgRgRgMQgXgQgbABQgeACgUAYIgDADIgaAbIAEgFQgbAegYARQgyAbgYAPIgIADIAEgBIgBABQgxATADA5QAEA2AzAEIgMALIAHgIIggAaQgfASg1AZQhDAfgTAKIAHgCQgVAHgOAGIgdAJIgBAAQggAAgVAVQgSAUgDAcQgCAdAPATQARAWAgAAQAgAAAdgKIgFACIA6gTIAWgHIgXANIgtAZIgBAAQghAbgnANQgjAPgiAJQhWAghiAAQhSAAhAgZgAnRSGIAAABIAMgEgAkBQVIADgDIAAAAgAj6QPIgBABIAKgEgAn9ykQgcAFgRAVQgUAXADAfQACAWAOAcQAHAaAMAWQALAZATAWIACAEQAJATATARQAJALAVATIAIAGQAUATAaAPIACABIADABIARAKQAMAIAVAKQAtAZAaAAQAfAAAVgWQATgUACgcQADgcgPgUQgRgWggAAIgBAAQAMgLAIgUQASgygmgiIgRgNIABAAIgigeIgUgWIgIgQIgCgHQgBgPACgKQAEgQAAgMQAAgfgVgVQgUgTgcgCQgcgDgUAPQgWARAAAgIAAAIIgCANQgKgEgMAAQgIAAgIABgAmPR7IABAAIgHACgAwXM2IAAgBQAMAbAQAaIgJAGQgMAKgFAPQgCgoAAgrgAiLNuIAKgDIAHAAIgSAEgAwPKnIAAgBIAAgBIAAAJIAAgHgAQWmLIgBAJIAAACIABgLg");
	this.shape_4.setTransform(-29.5868,63.3721);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.carrot, new cjs.Rectangle(-134.7,-201.9,269.5,403.9), null);


(lib.walking = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {walking:0,standing:10};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_9 = function() {
		// this.stop();
		
		this.gotoAndPlay("walking");
	}
	this.frame_11 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(9).call(this.frame_9).wait(2).call(this.frame_11).wait(1));

	// leg
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgpFJQgkgEgSgMIgFgDIgEgIQgIgSgEgcIAGAAQAFADADAFQABADABAHIADAKQAHANAZAGQA+AOA6gRIgCgHIgBgHQgHgagjgQQgKgFAAgEQgBgEACgEQACgDAFgBQAFgBALAEQAUAKAOARQAOASADAVIAAACIAHgDQAHgDACgDQAHgGgCgMQgDgWgQgPIgYgTQgPgOgMgdQgMglgCg0IABhbQgChoABg0QABgmAFghQAGgHABgHQABgEgBgBQAAgBAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAQAGgfALgbQAEgLAHABQAGABABAJQACAKgFAOIgIAXQgJAYgEApQgCAhAABDIAACMQgBBKAKAkQAHAeAPAQQAIAJATAPQAaAYAAAkQAAAQgGAJQgHAKgSAHQgsAPgyAAQgQAAgQgBg");
	this.shape.setTransform(56.05,4.0946);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AGqGxQghgCgRgKQgcgQgJgoQgEgGgBgGIgBgLIgDgKIAAgNIAAgEIAAgHQACgjgGgXQgDgQgMgeIgrhqQgHgSgFgIQgFgGgSgUQg/hBgnhUQgGgNAFgFQACABAEAAIAIgCIABABIAHALQAlBVBDBAIAPAQQADAFAIASIAoBiQASAsAGAZQAFAUAAASIACADQAEAFAAAHQABAPgBAfQADAHgBAFIgBADIABACIABAEQAEAQAIAKQANAOAWAEQAPAEAaAAQAdAAAUgCQgBgOgHgNQgHgOgMgJQgIgFgCgEQgGgGAFgGQAFgGAMAGQATALALAUQAJARACAUIAHgCQAWgHAEgMQACgIgDgLIgJgSQgKgUgDgiQgCglgDgTIgHgjQgFgWgCgNIgBgyIgHg2QgGgugBg5QgBgfACg3IgBgEQgBgmAEgSQABgFACgDQAGgBACgDIABAAQADABACACIgBABQAAACADACIABABQABADAAAFIgDANIgBARIAAAHIAABkQAAApACAUIAFArQAFAbABAQIACAzIAGAmIAHAnQADASADAlIABAHQAEAcAIASIAEAJIAEAKQAFALAAAIQAAAMgHALQgHAKgMAGQgQAJgfADQgWADgXAAIgdgBgAgFFsQgTgEgZgKIgrgRIgsgPQgbgJgQgHQgVgJgpgVQgigQhXgZQhPgXgogVQgHgEgDgDQgigZgpguQgIgJACgGQACgDAEgCQAFgBAEACQAEACAIAJIARASIAWAWQAWATANAGQAHACADADQAmATBHAVQBTAXAiAQQAxAaAZAKQAOAGAbAHIApAOQAjAPASAHQAhAMAagDQAjgEASgXQAFgGAEgLIgGgIQgXgjgogJQgTgEAAgIQgBgHAJgDQAGgCAIACQAMACATAKQAUAKAIAGQAGAFAHALIADAEQAFgTgBgMQgCgXgVgTQgRgRgcgLIgwgSQgcgKgQgOQgHgHgDgGQgBgEABgEIgigmQgcgigJgQQgOgZgLgzQgMg4gOhUIgLg5QgWhcg9hHIgBgBIAAgBQAAgEgEgCIAAgCQAAgFAEgCQAFgDAFABQAHACAIAJQAWAaAUAnQAkBHAMBAIAIAxQALBSANAvQAGAeAKARQALAXAfAhQAgAmALASIACADQALAJAQAHIAjANQAmAMAXATQAdAaAGAeQAGAdgPAlIgBAEIgCADQgPAegUAOQgXARghAAQgPAAgQgEg");
	this.shape_1.setTransform(-10.4211,0.0088);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AEkGgQgXgFgMgOQgJgKgEgPIAAgEIgBgDIABgCQAAgGgDgGQABgfgBgQQAAgHgDgFIgCgCQgBgSgFgUQgFgZgSgsIgohjQgIgSgEgFIgPgQQhDg/glhVIgHgMIgBgBIgHACQgEABgDgCIgBAAQgEgDgBgEQgBgHALgGQANgJAXgLQA8gbBngRIAbgEIAWgBIBogDQAMAAAFADQAEACACAEQACAEgCAEIgBACQgDACgGACQgCACgBAFQgDATABAlIAAAEQgBA4AAAeQABA5AGAuIAHA3IACAxQABAOAFAWIAIAjQADASACAmQADAhAJAUIAJATQAEAKgDAIQgEAMgWAIIgHACQgBgUgKgSQgLgTgSgLQgMgHgFAGQgFAGAFAHQADAEAIAFQAMAJAHANQAGAOABANQgUACgcAAQgaAAgPgDgAHjFeQgZgGgGgNIgDgKQgBgHgCgDQgDgFgFgDIgFAAIgBgIQgDglgDgSIgHgmIgGgmIgDg0QgBgPgEgcIgGgrQgCgUAAgpIABhkIgBgHIACgQIACgOQABgEgBgEIgBgBQgDgCAAgCIAAgBQABgDAFAAQAFAAAGADIALAGQARAIAagBQAPAAAegGQASgEAKgFQAPgGAGgLIAFgHQABgBAAAAQABAAAAAAQABgBAAAAQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAABQABABgBAEQgCAHgFAHQgFAhgCAmQgBA0ACBnIgBBcQACA0ANAlQALAdAPAOIAYATQAQAPADAWQACAMgGAGQgDADgHADIgHADIAAgCQgCgVgPgSQgNgRgVgKQgKgEgGABQgEABgDADQgDAEABAEQABAEAKAFQAjAQAHAaIABAHIADAHQghAKgiAAQgbAAgcgHgAiOFVQgSgGgigQIgpgNQgbgHgPgGQgZgKgxgaQgigQhTgYQhHgUgmgTQgCgDgIgDQgNgFgVgUIgXgVIAFgEQgDgCgCgFQgBgFACgJQAYhjAiiBQANgwAJgYQAMgfAbgyQAbgxARgYQAbgnAfgUQAJgGAHAAQAEgBAEADQADADABAEIAAABIAAAAQA+BIAWBcIALA4QAOBVAMA3QAKAzAPAZQAIAQAdAiIAhAnQgBADACAEQACAGAHAHQAQAOAcAKIAxATQAcALARAQQAVATACAXQABAMgEATIgDgDQgIgLgGgFQgHgHgUgKQgUgJgLgDQgJgCgFACQgKADABAIQABAIASAEQApAIAXAjIAGAJQgEAKgGAHQgSAXgiAEIgKAAQgXAAgcgKg");
	this.shape_2.setTransform(1.1333,-0.6286);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhOHfQgggJgNgKQgNgKgNgVIgRgcIADABQBMARAyAUQAEASgDAVQgHAFgLAAQgKAAgOgEgAjFHKQgMgDgEgDQgDgCgGgLIgZgzIALAFIAZAHIAJACIAEAAQgBAKAMAQQAOATALARgAAgG/IgCgBIgBAAQgVgMgdgMQgDgEgFgBIgEAAQgygShJgRQiAgdg5giQgRgKgDgLQgCgIADgKIAGgSQAEgVgLgVQgLgUgUgMQgRgKgYgHIgrgKQilghhkhMIgFgEQgCAGgFAAIgCgIQgDgTAGgWQAGgSAOgcQAjhEBRh9QAQgZANgRQAQgXAYgbIAqguQArgtAagSQAdgUBEgZIAEgBQAHgCACAEIgGAGQAEACAIABQAuAFAvAgQAjAXAsAtQAyAyAbApQAjA2AHA1QAGA0gUA8QgPAsgiA9QgpBLgmAiQgLAKgCAHQgBAGAEAEQACAEADAAQABAOACAHQAGAQAYAQQAcASAxAXIA4AcQARAJAKAHQAOALAFANIAGARQADAGADAEQABAkgBAhIgFABQgEAAgHgCgACGGaQgYgUgegLIgEgCQABgHgEgLIgHgSQgIgRgUgUQgGgFgDABIACgFIASgvIAHgSIAJAGQATALAfAZQAmAgAOAaQAKASADATQACAVgHARQgGAPgLACIgCAAQgJAAgNgMgAgGEhIhxg5QgRgKgHgGQgMgNgBgNIAAgOIAAgBQAxgyAig9QAQgdAVgtQAQgkAFgWQAFgUABgoIAAgXQAEACAEgDQADgDABgEQABgFgBgOQAAgIADgPQAFgbAFgNQAFgNAMgaIAJgWIAMgZQAfg2ARgYQADgDABgFIAAgFIgOgFIABgBQAIgKAWALQATAKAcAUIAtAhQASALAvAXQArAUAWAPQAfAYAQAKQAQAKAiAOQBCAbAqAXQA5AgAnAlQAWAVAIAFQALAGAXAHQAPAHAZAYIAHAGQgFADgHgCQgQAYgsARQhqArhxAKQhDADgiAEQguAFhFARQhCARgnASQg4AZgeAnQgRAVgNAfQgIATgNAnIgBABIgNgHg");
	this.shape_3.setTransform(-38.4089,-22.0202);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AiDCGQgWgCgRgEQgOgDgGgFQgHgGgGgLIgJgTIgNgWQgIgNgCgKQgBgHADgFIACgDQACgDAFAAIACABIAFAAQAFABAGAEIAKAFQAHADAKACIASAEQAFABACADIAAAAQACABABAIQACAJALANQASAXAJARIACAEIAAAAIgBADIAAAAQABAIgIADIgHABIgHgBgAi5BZQAGAKADADQADACAMAEIAkAGQgLgRgOgTQgMgQABgKIgEgBIgJgCIgagHIgLgFgAC5BdQgJgCgPgKIg3glIgBAAQgIgGABgFQAAgDADgBIABgDQACgDgDgFQgMglgVgQIgGgGIgBgCIAAAAQgBgDADgDIACgBQAEAAAFAFQAUAUAJARIAHARQAEALgBAHIAEABQAdAMAYAUQAPAMAJgBQALgCAHgPQAHgRgDgVQgCgSgKgSQgOgZgmghQgfgZgUgLIgIgFQgEgEABgFQADgGAIAAIACAAQAOABAOAKQAGAEARAQQAgAbAPAPQAZAaAGAZQAFAQgBAdQgBAdgIAMQgGAKgMAFQgIADgHAAIgJgBg");
	this.shape_4.setTransform(-42.0802,13.0167);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AhiHqQgigLgSgQIAAAAIgBgEQgKgRgSgXQgLgNgBgJQgBgHgDgCIAAAAIAAAAQgCgDgFgBIgRgEQgLgCgGgDIgLgFQgGgEgEgBIgFAAIgCgBQgFAAgDADQgtgPgbgOQgjgTgGgYQgCgLAEgXQAEgXgEgMQgIgdg1gMQiIgighgMQhdggg4gzQgHgGABgGQABgGAIABIACAIQAFAAACgGIAFADQBkBNClAhIArAJQAYAHARAKQAUAMALAUQALAWgEAUIgGASQgDALACAHQADALARAKQA5AiCAAeQBJARAyASIAEAAQAFAAADAFQAdALAVAMIABABIACAAQALAEAFgDQABgggBgkQgEgEgCgGIgGgSQgFgNgOgKQgKgHgRgKIg4gbQgxgYgcgRQgYgRgGgQQgCgHgBgNQgDgBgCgDQgEgFABgFQACgHALgKQAmgjAphKQAig9APgsQAUg9gGg0QgHg1gjg2QgbgogygzQgsgsgjgXQgvgggugFQgIgBgEgDIAGgFQgCgEgHABQABgDAEgCQAFgDAGAAQA3ABBEA0QBbBHA+BjQATAdAIAZIACALIADgJIACgPQACgOAIgUIAXg5IAOgaIAXgoQAOgYAIgJQAFgGAFgCIgBABIAOAFIAAAEQgBAFgDADQgRAYgfA3IgMAZIgJAWQgMAZgFAOQgFANgFAbQgCAPAAAIQAAAOAAAEQgBAFgEACQgEADgEgBIAAAWQgBAogFAUQgFAWgQAkQgVAtgQAeQgiA9gxAyIAAAAIAAAOQABAOAMAMQAHAHARAKIBxA5IANAHIABgBQANgoAIgSQANgfARgWQAegnA4gZQAngSBCgQQBFgRAugGQAigDBDgEQBxgKBqgqQArgRARgYQAGACAGgDIgHgHQADgGACgGQACgJADgCQAFgCAEAFQAEAEAAAGQAEAlg5AdQg9AhhIARQgwALhMAHIh9ANQg9AJg9ARQhpAfgoA3IgHALQgIAAgCAGQgCAFAEAEIgHASIgSAuIgCAFIgDABQgCADAAADIAAAAIABAAIABACIAGAGQAVAQAMAmQACAFgCADIgBADQgCABgBADQAAAFAIAGIAAAvQABAOgGAGQgFAIgUAAIgJgBIgEAAQgGAAgKgGQgLgHgOgHIAAAaQAAAOgEAFQgDAGgMADQgIADgKAAQgSAAgYgIgAiZGmQANAVANAKQANAJAgAJQAdAJANgKQADgUgEgSQgygUhMgSIgDAAIARAcg");
	this.shape_5.setTransform(-38.0023,-21.2971);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AyaGfQgrgNgbgcIgGgHIgDgEIgIgIIAAAAIgCgBQgFgCgEABQgGACgBAEQgBAFAFAHIAGAIQgDgCgFgCIgUgDQgNgCgIgDQgIgDgQgJQAlgDAsgUQATgJAcgQIAwgbIAegPQAQgKALgJQAYgVASgjQALgXAOgrQAMgnADgQIADgUIAFgUQAFgRAOgQQAHgKATgTIAAAAIABgBQAhggAVgNQAZgOAMgIQAWgQAKgZQALgYgDgbIAAgDIgGAAQgEgBgDgDIgBgBQgDgEABgEQABgDAGgEQATgKAUAAQAIABAOADQAPAEAHABQAOACATgDIAggGQATgCAbgBIAugBQAxgCBHgPQBPgSAogHQAKgCAEACQAEABACADQACAEgBADQAAAEgGAEQgGAEgBADIA3gBQgDgSACgPQABgKAFgDQAEgCAFAEIACADIADAGQABADgBAHIAAAEQALAsAEBSQACAngCAUQgCAngOAuQgJAcgVA3QgPAmgMAQQgPAUgaATQhGAyhsAVQgnAHg4AGIhcAJIgBAAQg2gHgwAMQg2AMglAgQgNALgcAgQgYAdgSANQgOAKgPAFQgKACgOAAIgKAAQgwAAgggJgAsoi5IgCAOQgCAMgGAQQgIAYgIAMQgZAqg7AKQgIABgEADQgHACgHAGQgOAKgJALQgKAKgFAKQgKAPgFAZIgHAtQgJA1gXAxQgKAYgMAPQgNASgWAQQgNAJgYAOIgBAAIgFADQgeARgQAEQgMADgEAEIgCACIg6AVQgMAEAAAHQABAGAFACQAFACAGgBQAKgBATgHIAZgKIARgDQAHgDAEgFQALgDANgHIAmgYQAkgWAFgEQAfgXAYg3QAWg0AJg3IAFgiQAEgTAGgNQAPgeAdgPIAGgEQAsABAjgkQAegdAPgyQAGgWgBgPIARgLQgLABgIgBQgGgBgEgCIgEgBQgEAEAAALgATZDJQABgCgBgEQgBgDgFgHQgeggg7goQhbg9hIgaQgcgKgUgDIghgCQhGgCgmAGQgGABgDACIgDgCQgEAEgEgCQgHgCAAgNIAAiJQAAgfgCgPIgFggQgPhBgGgWQgFgQgBgJIAAgXQAAgegXgbQgFgFAAgDQgBgGAGgDQAFgEAGACQADABAEAEQAEAEAEAHIAFALQAwBNA/BEQBTBZBYAyIAqAWQAbAOAPAKQAYAOA0ApQAvAkAdAQIAjAUQATAMAJAPQAKARAAAdQAAAZgIAQQgGAJgJAGQgJAGgKAAQgTAAABAIgAU2BCQgLgOgWgNIgmgVQgXgNghgZIg3gqQgXgQgngWIhAgjQgdgRgagTQAGABAKgDQAHgCABgEQACgDgBgEIgBgHQAAgDADgJQAFgKADgPIAOgtIAAgCICvB3IA0AiQAdAVAQAWIATAeIAXAkQAMAVABASQAAALgDAOIgHAXIgDgGg");
	this.shape_6.setTransform(-59.1594,-30.082);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("A0zFRQgIgEgLgHIgRgKQgLgHABgHQABgEAGgCIAAAAIAEgEQAEgCAJgBQAsgFAzgWQAegOA7ggQAfgRAPgLQAYgSANgUQAJgPALgiQARgxAHggQAIgnAFgMQAJgYAagcQAogrAugaIAUgNQALgIAGgIQAHgKAFgTQAFgZADgGIADgFQADAEAEAAIAGAAIAAAEQADAagLAZQgKAZgWAPQgMAJgZANQgVANghAgIgBABIAAABQgTATgHAJQgOASgFARIgFATIgDATQgDAQgMAnQgOAsgLAXQgSAjgYAUQgLAKgQAJIgeAQIgwAaQgcARgTAIQgsAUglADQAQAJAIADQAIADANACIAUAEQAFABADACIAEAFIAAADIAAADIgBABQgCACgEACIgMABQgjgEgTgJgAVKA1QgFgCgCgEQgCgGADgMIAAgDIAHgWQADgNAAgLQgBgTgMgVIgXglIgTgdQgQgWgdgVIg0gjIivh3IAAACIgOAuQgDAOgFALQgDAJAAACIABAIQABAEgCACQgBAEgHACQgKAEgGgCIgEgCIgBgBQgDgFACgIIAHgMQAJgPAHgaIAMgqIAEgIIgCgEQAAgEADgCQADgDAEAAQAGAAAIAFQASAKAeAVICnByQAcATARAPQAXAWAiA3QAQAaAFAOQAFAVgDAaQgDAQgIAdQgCAGgCACIgCABIgDABIgDgBg");
	this.shape_7.setTransform(-60.2613,-25.5273);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AyFHBQgigCgUgFQg1gLgkgnIgCgCIgCgCIgEgFIgFgHQgFgHABgFQABgFAFgBQAFgCAEACIADACIAAAAIAIAHIADAEIAGAHQAaAdArAMQAkALA2gBQAPAAAKgDQAPgEAOgLQARgNAZgcQAcggAMgLQAmggA1gNQAxgLA2AGIABAAIBbgIQA4gGAogIQBsgUBGgyQAagTAOgUQAMgRAPgmQAWg2AIgdQAPguACgnQABgTgCgoQgEhSgLgrIABgFQAAgGgBgEIgCgGQABgEAEgBQAGgCAFAFQAEAFACAHQAMAwADBcQACAxgCAZQgEAmgOAsQgJAcgUAzQgOAkgMARQgQAYgfAVQhKA1hxAXQgsAKg4AFQgeADhIAFQgJAAgDgDIgBgBQgtgBgpANQgxAPghAfQgQAPgdAjQgaAdgZAJQgQAHgWABIgHAAIgggBgA0SFnQgGgDgBgFQAAgHANgFIA6gVIACgCQAEgDALgDQARgFAegRIAFgDIAAAAQAYgOANgJQAWgQAOgRQALgQALgXQAWgxAJg2IAHgsQAGgZAJgRQAGgJAJgKQAKgKANgLQAIgFAGgDQAFgCAIgBQA7gLAZgpQAHgMAJgYQAFgRADgLIACgOQAAgMADgEIAEACQAEACAHABIABAFIABAFQABAPgGAWQgQAzgdAdQgkAjgsAAIgGAEQgdAOgOAeQgHANgDAUIgGAiQgJA3gWAzQgYA3gfAYQgEAEgkAVIgnAYQgMAHgMAEQgEAFgHACIgQAEIgZAKQgTAHgLABIgEAAIgGgBgATbDXQgFgDgBgEQAAgHASAAQAKAAAKgGQAJgGAFgKQAJgPAAgZQAAgdgLgSQgIgPgTgMIgjgUQgdgQgwgkQgzgogYgPQgQgKgagNIgqgXQhYgyhUhZQg+hEgwhNIgGgLQgEgHgEgEIgLgTQgEgHACgEQABgDAEgBQADgCAEACQAFABAGAIQAJANANAUIAUAhQBKB4BxBTIABABIADACQAbATAdARIA/AkQAnAVAYAQIA3AqQAhAaAXANIAmAUQAVANALAPIAEAFIgBADQgDAMADAGQABAEAFACQADABADgBQAFARAAAWQgBAngSAVQgLANgQAEIgMACQgKAAgIgGgASiDMQgNgNgOgMQhXhIhqguQgygWghgCIgeAAIhYACQgJAAgEgBQgHgEABgGQABgDADgCQAEgCAFgBQAngGBFACIAiACQATACAdAKQBIAaBbA9QA7ApAdAfQAGAHABADQABAEgBADQgBADgCABIgFACQgFAAgIgIg");
	this.shape_8.setTransform(-55.7083,-30.5312);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("APQOKQgOgCgYgMQgegPgIgOIgGgNIgGgOIgBAAIACAAQAGgBACgFQADgEgDgGIgFgJQgGgJgFgRIgHgcQgHgQgVgbQhChTg2heQgagsgSgoQgvhlgVhvQgVhuAHhvQABgOgDgFIgEgDIgCgBIgBgBQgEgCAAgCQgBgFAFAAQACAAAFACQASAGAbAFIAvAHIAdAGIBJASQAtALAWAHQAUAHAMABQAUADAEABIABABQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABQAAAEgEABQAAAEAEAHQAhA2AVBNQANAwAQBbQAHAjADAZIACAnIABAnQABBKAMBIIAJAyQAEAcgCAWQgBAMACAEQgBAFAEAJQAHAOAHAGQAFAFALAHQALAHAFAFQAEAEALAQQAFAKAAAFIgDAHIgEAHIgFALIgKANQgJAKgFAEQgKAHgPACQgIABgTAAIgaABIgTgBgARpNHQgBgTgOgQQgJgLgUgOQgMgJgEgFQgFgMgEgFIgDgCQAEgagEgiIgJg7QgMhQgDhRIgBgoIgCgnQgCgRgHglIgHgkQACABAEgBIABAAIACABQADAAAEgEIAGgFIAIgCQAGgDAHgGIAOgMIAngdQAMgJAOgPQgDALgDAOQgKBCgBBAQAAATABAJIAIAfQAFAUABAdIABAzQADCMBFBYIAOASQAGAKABAKQAAAOgLAMQgJALgPAFQgLAEgRACIgdADQgFABgCACIAAgIgAs3CQQgJgDgNgQQgMgPgJgEQgDgCgDABIABgGQAFABAEgDQAFgEAEgNIAbhRIAFgaIABgdIAAgyIgBgbIgDgOIgFgTQAmAMAtASIADABQADAMAHAOIAOAcQALAUAHATQALAZADAQQAIAjgOAlQgNAkgcAaQgKAJgIACIgPACIgiABQgQAAgGgDgAv/AaQgUgCgKgKIgFgHIgGgFIgFgCIACgDQACgEAAgJQABg2gKhDQgGgpgRhOIgHgeQggh/hbheQAWgBAmgGQArgIASgBQBNgHAnAnQAQARALgEQAGgDACgJIgBgSQgEgqAmg7QA+hgBbhHQBbhIBrglQALgEABgGIAAgCQgBgBAAgBQAAAAAAgBQgBAAAAgBQAAAAgBAAIAAgBQABgFAIABQAIACANAGQCjBIBuCKIAUAYQAOAQARAOIAEAEIACABQACAFgEACIgBAAQAABIgGAyQgIBCgVA0QgeBLhABHIgBACQg+AzhLAVIgkAJIgPADQghAHgMAAQgUACgbgDIgwgGQgKgBgFAEIgPgCQgTgDgRgFQgkgLg8ggQgygZgSgXQgHgIgPgaQgNgWgLgLQgFgFgEABIgDABIgCgBQgEgCgEACQgFADACAMQAEAcAFARQADALAJASIANAdQAOAkACA2QAAAZgEAMIgJAYIgJAZQgKAZgZAOQgVANgXAAIgIgBg");
	this.shape_9.setTransform(-88.9114,-83.8341);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AO6INQgGgBgEgDIgBgCQgCgDABgDIACgDQADgCAEAAIAdgDQASgCALgEQAOgFAKgLQALgMgBgOQAAgKgHgLIgNgSQhFhXgEiNIgBgyQgBgdgFgVIgHgfQgCgJAAgTQABg+ALhCQACgPAEgLQgOAQgMAJIgnAcIgPANQgGAFgHADIgHACIgGAFQgFAFgDgBIgBgBIgCABQgEAAgCgBIgBgBQgDgDADgDIABgCQACgCAFgCIAMgFQAPgLAQgNIBCg4IAMgJIACgBIAFgGQACgDACgBIADAAQAHgGAGADQADACABAFQABAEgBAEQgBADgEAEIgFAHQgIALgEAdIgJBFQgEAbABAKQAAANAHAhQAFAdAFBkQAFBRAQAuQANAoAYAgIAPAUQAIAMAFAJQAOAbgIAWQgGARgWAOQgcARgfAAQgLAAgLgCgAv2iqQgKgDgLgLIgRgUQgJgIgCgEQgCgEABgEQABgFADgBIADgBQADAAAEACQAIADANAQQAMAPAJAEQAGACARAAIAiAAIAOgCQAJgDAKgJQAcgZANgkQANgmgHgjQgEgQgKgZQgIgTgKgVIgPgcQgHgOgCgMIgEgBQgsgRgmgNIAFATIACAPIABAaIAAAyIgBAeIgFAZIgbBTQgEAMgFAEQgEADgFAAQgFgBgCgEQgCgEADgJQAPgoALgkQAJgZABgRIABgEIAAgTIAAgqQABgPgCgLIgDgPQgEgSgDgJIgEgKQAAgIAEgCIAAAAIADgBQAQAOATAIQAJAEAVAGQAfAJAdAFIADAHIAAACQADAKAHAMIAMAXQAHANALAbQALAbACAOQADALAAAYQAAAfgFAPQgEAOgJAQQgPAZgVAWQgRAOgMADIhDABQgKAAgFgBg");
	this.shape_10.setTransform(-70.4712,-50.1638);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AQTOUIgRgBIgTgGQghgMgRgPQgZgWgEgaQgBgGACgEQACgFAEgBQgEgFgDgMQgLgogWgjQgLgTgngyQiAiog0jJQgIgegFgaQgKg1gDhAQgCgsABhJQAAgIACgDQADgDAGABIACABIACABIAEAEQADAFgBANQgHBvAVBuQAVBvAvBlQASAoAaAsQA2BeBCBTQAVAbAHAQIAHAcQAFARAGAJIAFAJQADAGgDAEQgCAFgGABIgCAAIABAAIAGAOIAGANQAIAOAeAPQAYAMAOACIATABIAagBQATAAAIgBQAPgCAKgHQAFgEAJgKIAKgNIAFgLIAEgHIADgHQAAgFgFgKQgLgQgEgEQgFgFgLgHQgLgHgFgFQgHgGgHgOQgEgJABgFQgCgEABgMQACgWgEgcIgJgyQgMhIgBhKIgBgnIgCgnQgDgZgHgjQgQhbgNgwQgVhNghg2QgEgHAAgEQAEgBAAgEQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAIABgBQAFgGAJAFQAEADAFAJQAeA2AVBJQAJAhAMA5QgCAEADADIABABIAHAkQAHAlACARIACAnIABAoQADBRAMBQIAJA7QAEAigEAaIADACQAEAFAFAMQAEAFAMAJQAUAOAJALQAOAQABATIAAAIIgDADQgBADACADIAAACQgDAJgDAFQgFAKgIAKIgMAOQgLAJgOAHQgLAFgHABgAvdAfQgWgIgIgUQgDgGADgEIAAgBIgBAAQgGgCAAgPQABgrgHg2QgEgigNg+QgQhTgQgsQgUg1ghgtIgug7QgGgJgBgDQgBgGADgCQgCgDAAgDQAAgGAOgEQBGgPBDgDQAlgCAWAGQALAEAUAJQAUAKAKAEQgHgaAWgrQAuhZBOhLQBJhGBfgzQAygbAmgJQAHgCAHACIAEADQABAAAAAAQAAABABAAQAAABAAAAQAAABABABIAAACQgBAGgLAEQhrAlhbBIQhbBHg+BgQgmA7AEAqIABASQgCAJgGADQgLAEgQgRQgngnhNAHQgSABgrAIQgmAGgWABQBbBeAgB/IAHAeQARBOAGApQAKBDgBA2QAAAJgCAEIgCAEIAFACIAGAFIAFAGQAKAKAUACQAbADAZgPQAZgOAKgZIAJgZIAJgYQAEgMAAgZQgCg2gOgkIgNgdQgJgSgDgLQgFgRgEgcQgCgMAFgDQAEgCAEACIACABIADgBQAEgBAFAFQALALANAWQAPAaAHAIQASAXAyAZQA8AgAkALQARAFATADIAPACQAEgEALABIAwAGQAbADAUgCQAMAAAhgHIAPgDIAkgJQBLgVA+gzIABgCQBAhHAehLQAVg0AIhCQAGgyAAhIIABAAQAEgCgCgFIgCgBIACgDQADgDAEACQAEABADADQADAFAAALQAABYgHAxQgQBrg9BZQgUAcgZAcIgGAHIgCABIgLANQgkAlgeAOQgVAJgoAIQggAGghAEQgaAFgSAAIgTAAQgSABgYgBIgLAAIgIgCQgqgEgdgHIgBgCIgDgHQgcgFgfgJQgWgHgIgEQgUgIgQgOIgCABIgYgNQgYgQgNgSQgHgIgLgUIgJgQQADARALAXIASApQAMAiAAA3QAAAbgCANQgDAOgEALQgFAOgMAWQgKATgHAHQgYAcgsACIgJABQgTAAgOgGg");
	this.shape_11.setTransform(-94.8026,-82.7321);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},2).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},2).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9}]},2).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},2).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},2).wait(2));

	// head
	this.instance = new lib.head();
	this.instance.setTransform(19.25,-145.85);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2).to({y:-141.85},0).wait(2).to({y:-145.85},0).wait(2).to({rotation:8.4648,x:23.25,y:-142.95},0).wait(2).to({rotation:0,x:19.25,y:-141.85},0).wait(2).to({y:-145.85},0).wait(2));

	// body
	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AjAJqQg1AAhIggIgCgCQgCgDgEgCQgfgPgagaQgFgFgCgBIgFgBIgGgFQgNgIgPgLIgTgRQgbgagSgkQgHgQgFgHQgLgSgFgJQgFgLgEgQIgRg8IgFgKIAAAAIAAgBIgEgLIgGgbQgKh1AmiSQAJgkAJgVQANgcApgzQAWgcAPgRIACAAQADAAAFgDQAGgEARgOIAWgUIADgFIACgCQAMgJAKgGIAAgBIADgCQADABADAAQAGAAAKgHICThiIAVgPIAoghQAVgQAQgPQAagYArg7QAbglAOgaIALgXIAJAXQALAbAFAJQAJAPAPAQQAcAbAzAeQB8BJBoAJQgfBlAGBpQAHBxAyBeQAKAUALAQQAMARAMAMQAYAZAmAUQAXANAwAUIBFAcIAFAEIAUABIADAAQASAEAPgDIgaAjQgVAegfAiIg5A7QgoAogZAVIgiAaQhLA1hWAkQgFgGgPACQhuARhsgQQgKgBgEACIgBgBIgCACIgKgDIgGgDIgPgMIgUgNQgNgKgNgSIgUghIgagoQgPgXgGgTQgFgLgDgUIgTheQgGgBgCAHIAAAMIATBdQAGAZAQAdQAJARAVAgIAQAZQARAYAJAJIAHAGQgwAJg3AdQglAShDArQgJAFAAAGQgFgDgHAAgAowHaQhggeg9hPQgigsAKgiQAEgPAVgXQAPgPAJgEQAMgFAXABQAbABAJgCQAiAgARApQADAKAFADQAHAjAMAeIACAHIACAEQAOAiAVAeQAIAPALANQgMAEgOAAQgWAAgbgJg");
	this.shape_12.setTransform(-20.3136,-38.975);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AmCJmQg9gegwguQgMgKgJgKQgHAFgOABQhFADhDgjQg8ghgvg6QgWgcgFgUQgEgOAAgTQAAgOADgJQAEgQAWgXQAXgbARgEQAIgCARAAIAkAAQANAAAIADQANAEANASQAHAIAJAQQgHhWAQhrQAKhNAUgvQAUgzApgzQAeglAzgxIADgDQABgDAEgDQAOgKAVgNIADAAQACgEAFgEQAVgPA1giIBghCIA3gpQA0gvAvg/QAmgzAHgpQACgIACgFIADgDQACgEAFAAQAHAAAEAMIASAvQALAeAJAOQAMARATAPQAUASAQAKIApAYIAxAaQBQAmBZAIQAIABAEACIAFAEIAUgBQAYAAALgBQATgDAbgHQA5gQAzgRQARgGALgGIAMgJIAGgEIACgCIgBAAQABgFAHAAQAFAAAFACIAQAJQA+AlAkBXQAlBfgFCRIgBAaQgEA2gFAZQgPBXgtBLIgMARQgHAJgHAFIgBACIgIAJQgIAHgIAMIgNAWQgJAOgVAXIgdAfQg1A4geAcQgvAtgsAeQgoAahRAoQgLAFgIABQgCAFgEACQgGAEgNABQhJAEglAAQg9gBgwgIQgLgDgDgEIgMgEQgJgEgOgJIgJgGIgOAEIgdAGQgbAHggAQQgTAKgkAVIhEAoQABACgCADIgMAAQhIAAhOgkgAjjKBQAAgFAJgGQBCgqAlgTQA4gcAxgJIgHgGQgJgJgSgZIgQgYQgVgggKgSQgPgcgHgZIgSheIgBgLQACgIAHACIATBeQADATAEAMQAGATAPAXIAbAnIAUAhQANASANAKIAUANIAPAMIAFADIALADIACgCIAAACQAFgDAJACQBsAQBugRQAQgDAFAHQBVgkBMg2IAhgZQAagVAngpIA5g7QAggiAVgeIAZgiQgOACgTgEIgCAAIgUAAIgGgFIhEgcQgxgUgWgMQgngVgYgZQgMgMgMgRQgKgQgLgTQgxhfgHhxQgHhoAfhlQhngKh9hIQgzgegbgcQgQgPgIgPQgGgJgLgcIgIgWIgLAXQgOAZgcAlQgrA7gaAZQgQAPgUAQIgpAgIgUAPIiUBiQgKAHgGAAQgDABgCgBIgEACIAAAAQgKAGgLAKIgCACIgEAEIgWAUQgQAPgHAEQgFADgCAAIgCAAQgPAQgXAdQgpAzgNAcQgJAVgJAkQglCRAKB2IAGAbIADALIABAAIAAABIAEAKIARA8QAFAPAFALQAEAKAMARQAEAIAHAQQASAkAbAZIAUARQAOAMANAIIAHAEIAEACQADABAEAEQAaAaAgAQQAEACACACIABACQBIAhA2gBQAGAAAGADgArjD7QgKAEgOAOQgWAYgEAPQgKAhAiAsQA+BQBgAeQAsAOAfgJQgLgOgJgOQgUgfgOgiIgDgEIgCgGQgMgfgHgjQgEgDgEgJQgQgqgjgfQgJACgbgCIgGAAQgSAAgKAFg");
	this.shape_13.setTransform(-15.5706,-41.0109);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AkCHiQhzgHgZgEQhPgJg1gcQgigSg2guQhAg3glgpQgzg4gZg4QgDgHgGgCQgDAAgCABIgXgoQAEgCABgFQAAgFgBgDQgIgSgXgLQgKgFghgJQgogKgSgOQgNgJgRgVQgIgHgEgJQgEgIAAgSIAAgzQAAgUADgKIAFgUIAJglQAEgWAHgOQAFgKANgRQADgEAEgCQAFgDAIAAQATgBAJACQAJACALAGQAUANAMAbQAFAIAMAnQACAHADADQAEAGAHgDQAFAAABgFIALABIgBAEQAAAHADAHQAEAFAGgCQAFgBACgKQAHgfAIgRQAKgVAegoQAsg4AagdQAqgsAqgbQBIgvBpgRQBUgNBuAGQCpAKBzAsIA7AXQAlAQAXAHIAHABIAFAAQAFAAAGgGIAQgSQAWgaApgUQAdgOA7gSQAZgJANgCQALgCAVgBIACAAQgBAXALAiQATBAAQAeQAcAzAqAXIAZANIAZALIAVALIAWAKIAlAKIAaAGQAPACANABIB1AQQgFBvAIBtQADAkADARQAGAZAOAlQAUA2ASAfQAaAsAiAbQATAOgSAjQgfAWgdARQgeASiCAPQiCAOjJggIiUgbQhWgMg/AHQgHABgCADIgCgCIATgUQATgUAkgpQAjgoAQgWQAFgHAAgIQABgJgIgBQgJgCgIAOQgMAWgUAZIgnArQg5A9gjAeQg5Aug4ARQgvAQhBgBQgTAAhggEg");
	this.shape_14.setTransform(-63.4622,-61.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("AjcH5IhjgFIh9gHQhIgGgygSQg1gSg1gnQgngdg0gzQgrgrgaggQgjgrgQgpQgDgHACgHQABgDACgCQACgBADAAQAGACADAHQAZA3AzA5QAlApBAA3QA2AuAiASQA1AbBPAKQAZADBzAHQBgAFATAAQBBAAAvgPQA5gRA4guQAjgeA5g9IAngrQAUgZAMgWQAIgOAJABQAIACgBAJQAAAHgFAIQgQAVgjApQgkApgTAUIgTAUQgVAVgUAQQhHA8hNARQgkAIgvAAIgPAAgAFuGtIiLgYQhQgMg7AEQgJAAgHgEQgHgEAEgFQACgDAHAAQA/gHBWAMICUAaQDJAhCCgPQCCgPAegRQAdgRAfgXQASgigTgOQgigbgagsQgSgfgUg2QgOglgGgZQgDgRgDgkQgIhuAFhvIh1gPQgNgBgPgDIgagFIglgLIgWgKIgVgLIgZgKIgZgNQgqgXgcgzQgQgfgTg/QgLgiABgXIgCAAQgVABgLACQgNACgZAJQg7ASgdAOQgpAUgWAaIgQASQgGAFgFABIgFAAIgHgBQgXgIglgPIg7gYQhzgripgKQhugGhUANQhpARhIAvQgqAbgqAsQgaAcgsA5QgeAngKAWQgIARgHAfQgCAKgFABQgGACgEgGQgDgGAAgHIABgEQADgdATghQANgWAegmQArg2AWgWQBFhIBXglQAxgWA8gKQAugIA7ABQAiAABIAEIBdAHQA0AFAnAJQA0ALA9AXQAlAPBEAdQASgXAUgQQAagVAogRQAZgLAwgPQAZgIANgDQAWgDATABIAFABQAAAAABAAQAAgBAAAAQABAAAAAAQABAAAAAAQAJgBABAPQAEAiAXBCQAPAqAMASQAlA5BlAhQAUAHAaAHIAgAIQAwAKBUAHQAKAAAEADIABAAQA7AAAhgDQAygGAkgRQANgHAHACIATgLQAAgEADgCQAEgEAGADIAAAAIAIABQAEACABADQAAADgCAEIABADQAwCbgJCKQgKCMgsA5QgsA6gCAHQgDAHgHACQhBA5gpAXQgqAWhUAIQhGAGhHAAQh8AAh9gUgAuZBnQgNgQgegIIgZgGQgQgEgJgFQgegMghglQgLgNgFgIQgGgNABgaIABg5QAAgTACgJIAGgVIAHgiQAFgVAFgNQAGgLAPgWQAHgKAGgEQAHgEASAAQAiAAAQAGQAOAHANANQAaAbAQA6QACAIgBAFQgBAEgFABQgHADgEgGQgDgDgCgIQgMgmgFgJQgMgagUgNQgLgGgJgCQgJgCgTABQgIAAgFADQgEACgDAEQgNARgFAKQgHANgEAXIgJAlIgFAUQgDAKAAAUIAAAzQAAASAEAIQAEAIAIAIQARAVANAJQASAOAoAKQAhAJAKAEQAXAMAIARQABAEAAAFQgBAFgEABIgDABQgGAAgIgLg");
	this.shape_15.setTransform(-56.2543,-61.5929);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AlWHiQg8gCgsgMQhSgVhMg/Qg8gxg+hTQgWgegDgSQgCgMgFgCQgFgCgEAFIgegmQAEgDgBgEQgBgGgGgDQgXgRgygcQgtgcgTgeQgJgPgJgYQgSgzADgnQAAgMAEgHQADgEAFgFIAJgIIAJgJQAGgGAFgCQAFgDAKAAQAPgBAHACIARAGQA6AZAkA4QAEAIAGAEQADACAEAAQAFAAACgDQADgDgBgFIAAAAQAEgGABgNQAJhvBMhgQBIhcBsgxQC9hWEHAvIBoAWQBBAOAqAFQBAAICCAAQAzAAAfgIQAogLAWgZQADApAJAoQAJAjAJAVQAVAuAuAjQApAfA4ATQAzASBhAQQBHANAsADIgcA4QgNAagFAOQgLAcgLA8QgEAWgBANIAAAoQAAAYgDAwQgEAwAAAYQABAsANAZIADAEQgVATgWAQQhCAxhIATQhHAThYgHQhDgFhcgWIidglQhbgUhEAAQhdgBhZAeQhYAehIA4IhJABIgVAAg");
	this.shape_16.setTransform(-68.4406,-64.9138);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AlSH6QgEgCAAgEQg5ABgfgCQg5gDgsgKQghgHgYgLQgRgIgggUQhNgygjglQgNgNgdglIgjgtQgNgRgGgKQgIgQABgOQABgHADgEQAEgFAFACQAFACACAMQADASAWAeQA+BTA8AxQBMA/BSAVQAsAMA8ACQAYABBGgCQBIg4BYgeQBageBcABQBEAABbAUICdAlQBcAWBDAFQBYAHBHgTQBIgTBCgxQAWgQAVgTIgDgEQgNgZgBgsQAAgYAEgwQADgwAAgYIAAgoQABgNAEgWQALg8ALgcQAFgOANgaIAcg4QgsgDhHgNQhhgQgzgSQg4gTgpgfQgugjgVguQgJgVgJgjQgJgogDgpQgWAZgoALQgfAIgzAAQiCAAhAgIQgqgFhAgOIhpgWQkHgvi9BWQhsAxhIBcQhMBggJBvQgBANgEAGIAAAAQABAFgDADQgCADgFAAQgEAAgDgCQgGgEgEgIQgkg4g6gZIgRgGQgHgCgPABQgKAAgFADQgFACgGAGIgJAJIgJAIQgFAFgDAEQgEAHAAAMQgDAnASAzQAJAYAJAPQATAeAtAcQAyAcAXARQAGADABAGQABAEgEADQgEADgFAAQgFAAgLgHQgXgPgwgdQgogagTgcQgOgVgNgjIgJggQgEgQAAghQAAgYAFgLQAEgJAKgKIASgQQAPgOAHgCQAEgBAGABIALABQASgCAJACQAJACAOAHQAaAOAPALQAVAOANARIAQAYQAGhaAzhUQA3hbBag8QBVg4BsgYQBkgWBuAGQBDAEDOAmQCpAfBogHQBjgHAngyQAFACABAGQAGABADANIAMBCQAGAhAEAPQAIAbALASQAVAhA2AhQA0AgAmALQASAGAaAEIAtAHIBwAVQBAAIAtgOQAPgFAegNQAbgLATgBQAKAAACAGIABACQACAFAAAIQgDBJgeBlQgxCohNBrQgvBAg6AuQhAAxhGAWQhaAdh4gMQhIgHiMghQiHgfhOgGQh2gJhaAhQgmAOgrAaQgWANghAXIgBABQgBAFgEACQgEADgIABIgCACQgGAEgFAAIgEAAg");
	this.shape_17.setTransform(-60.3208,-64.6144);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AAbMOQhsgdhfgzQhFglg7gvIgFgCIgMgGQgKgHgMgEQgHgCgDgDQgDgCgBgFIAAgBIjuifIiChXQhIgyg2grQg+gygkgrQgug6gMg7QgHghADhBQAEg/AGgrQAJg5ASguQAQgqAYglQgCgFAAgNQACgzACgZQAFg+AMgoIALgjIAWg/QAJgcAKgVQAchAA4gqQAXgQASgEQAYgHAUANQAQAMAFAYQADANgBAdQAABLgCAlQgCBAgKAuQgCAJgFAEIAjgDIBOgJQAwgFAegBQCpgFDJBgQBHAiA/AnQB2BICCByQBOBFCTCPQAJAJACAHIADAEQADAEAAALQgFAtgBAXQgDAnAKAbQAFAQAWAmIAbAzQAQAdAQARQAXAYApAWQBZAxBZAHQARABAjAAIBWABIAJgBQALgBARgGIAGgBIADABIADABQAGAEgDALQAAAEgDAEQgvBihSBLQhTBNhnAmQheAjiNAKQg5AEg3AAQisAAiUgogAkpJRIAKAIIADAEQCLBxDBAwQCtArDYgLIATgBIAAgBQgHgfAEgVQAFgTAOgTQAWgcApgSQAbgMAygMIAogLQARgGAUgKQAxgZAxgiQAogbANgZIAGgKQgogBgQgCQgqgGg4gVQhZgkgrgwQgTgVgTgiIgeg8QgRgggFgPQgDgPAAgeQABgxAEgrIgGgGQg7hFhVhMQg0guhphWQg9gzgpgdQh8hciPg4QiIg1h0gFQgngCgxADIhZAIQhSAIgqAOQg7AUgwAvQgtAsgdA7QgyBlgDCSQgCA6AKAlQAMArAhApQAZAgArAmQBSBHCFBYICqBwQBTA2A7AtIAFgBQARAAAYAVgArmsZQhKAkgoBnQgJAWgJAfIgbBVQgGAdgGA5IgCAiQgBAOAAAJQAggnAqggQAzgkAxgNQAOgDAbgCIgCgCQgEgCgBgEQgBgFADgKQAMguAChCQABgmgBhMQABgSgDgLQgEgRgOgFIgIgBQgKAAgMAGg");
	this.shape_18.setTransform(-64.85,-128.4161);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AB6L+QjBgwiLhxIgEgEIgJgIQgcgYgSAEQg8gthSg2IiqhwQiFhYhShHQgrgmgZggQghgpgMgrQgLglACg6QAEiSAxhlQAdg7AugsQAwgvA6gUQAqgOBTgIIBZgIQAxgDAnACQB0AFCIA1QCOA4B9BcQApAdA9AzQBpBWA0AuQBVBMA7BFIAGAGQgFArgBAxQAAAeAEAPQAEAPARAgIAfA8QATAiATAVQArAwBZAkQA4AVAqAGQAQACAnABIgFAKQgNAZgoAbQgxAigxAZQgVAKgQAGIgoALQgyAMgbAMQgpASgWAcQgPATgEATQgEAVAGAfIAAABIgSABQguACgrAAQijAAiJgigAtJmMIACgiQAFg5AHgdIAahVQAKgfAIgWQAphnBKgkQARgIAMADQAOAFAFARQADALgBASQABBMgBAmQgCBCgMAuQgDAKABAFQABAEADACIACACQgaACgOADQgyANgyAkQgqAgggAnQgBgJACgOg");
	this.shape_19.setTransform(-72.216,-128.4047);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AkCHmQhzgHgZgDQhPgKg1gcQgigSg2gvQhAg3glgqQgzg5gZg3QgDgIgGgBQgDgBgCACIgXgqQAEgBABgFQAAgEgBgEQgIgTgXgLQgKgEghgJQgogLgSgOQgNgJgRgUQgIgIgEgJQgEgJAAgRIAAg0QAAgVADgJIAFgUIAJglQAEgYAHgNQAFgKANgRIAHgHQAFgDAIAAQATgBAJADQAJABALAGQAUAOAMAaQAFAJAMAnQACAIADACQAEAGAHgCQAFgBABgFIALABIgBAFQAAAHADAGQAEAGAGgCQAFgBACgLQAHgfAIgRQAKgVAegpQAsg5AagcQAqgtAqgbQBIgvBpgSQBUgNBuAHQCpAKBzArIA7AYQAlAQAXAHIAHABIAFAAQAFAAAGgGIAQgSQAWgaApgUQAdgOA7gTQAZgIANgDQALgBAVgBIACAAQgBAWALAjQATBAAQAfQAcAzAqAYIAZANIAZAKIAVALIAWAKQAHADAeAHIAaAGQAPADANABIB1APQgFBwAIBvQADAlADARQAGAZAOAmQAUA2ASAfQAaAtAiAbQATAPgSAiQgfAWgdASQgeASiCAPQiCAOjJggIiUgbQhWgMg/AGQgHABgCADIgCgBIATgVQATgTAkgqQAjgpAQgVQAFgIAAgIQABgJgIgBQgJgCgIAOQgMAXgUAYIgnAsQg5A+gjAeQg5Aug4ASQgvAPhBAAQgTAAhggFg");
	this.shape_20.setTransform(-62.4622,-61.1);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AjcH+IhjgGIh9gGQhIgGgygSQg1gTg1gnQgngeg0gzQgrgrgaggQgjgsgQgqQgDgHACgGQABgEACgBQACgCADABQAGABADAIQAZA3AzA5QAlAqBAA3QA2AvAiASQA1AcBPAKQAZADBzAHQBgAFATAAQBBAAAvgPQA5gSA4guQAjgeA5g+IAngsQAUgYAMgXQAIgOAJABQAIACgBAJQAAAHgFAIQgQAWgjApQgkApgTAUIgTAUQgVAVgUARQhHA9hNARQgkAIgvAAIgPAAgAFuGxIiLgYQhQgNg7AFQgJAAgHgEQgHgEAEgFQACgDAHgBQA/gHBWANICUAaQDJAhCCgPQCCgPAegRQAdgSAfgWQASgjgTgOQgigbgagtQgSgfgUg2QgOgmgGgZQgDgSgDgkQgIhvAFhwIh1gPQgNgBgPgDIgagGQgegHgHgDIgWgKIgVgLIgZgLIgZgMQgqgYgcg0QgQgegThAQgLgjABgWIgCAAQgVAAgLACQgNADgZAIQg7ATgdAOQgpAUgWAaIgQASQgGAGgFAAIgFAAIgHgBQgXgIglgPIg7gYQhzgripgLQhugGhUANQhpARhIAwQgqAbgqAtQgaAcgsA5QgeAogKAWQgIARgHAfQgCAKgFACQgGACgEgGQgDgGAAgHIABgFQADgdATgiQANgWAegmQArg2AWgXQBFhIBXgmQAxgWA8gKQAugIA7ABQAiAABIAEIBdAHQA0AFAnAJQA0ALA9AYQAlAOBEAeQASgXAUgQQAagWAogRQAZgKAwgQQAZgIANgDQAWgEATACIAFABQAAAAABAAQAAAAAAgBQABAAAAAAQABAAAAAAQAJgCABAQQAEAiAXBDQAPAqAMATQAlA5BlAiQAUAHAaAHIAgAIQAwAKBUAGQAKABAEADIABAAQA7AAAhgEQAygFAkgRQANgHAHACIATgMQAAgDADgDQAEgDAGADIAAgBQAEAAAEACQAEACABADQAAADgCAEIABACQAwCdgJCMQgKCMgsA7QgsA6gCAHQgDAIgHABQhBA6gpAXQgqAWhUAIQhGAHhGAAQh9AAh9gVgAuZBoQgNgQgegIIgZgHQgQgEgJgEQgegNghglQgLgNgFgIQgGgOABgaIABg5QAAgTACgJIAGgVIAHgjQAFgVAFgNQAGgMAPgWQAHgKAGgEQAHgEASAAQAiAAAQAHQAOAGANAOQAaAbAQA7QACAHgBAFQgBAFgFABQgHACgEgGQgDgCgCgIQgMgngFgJQgMgagUgOQgLgGgJgCQgJgCgTABQgIAAgFADIgHAHQgNARgFAKQgHANgEAXIgJAlIgFAUQgDAKAAAVIAAAzQAAASAEAIQAEAJAIAIQARAVANAJQASAOAoAKQAhAKAKAEQAXALAIASQABAEAAAFQgBAFgEABIgDABQgGAAgIgLg");
	this.shape_21.setTransform(-55.2543,-61.0981);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_13,p:{x:-15.5706}},{t:this.shape_12,p:{x:-20.3136}}]}).to({state:[{t:this.shape_15},{t:this.shape_14}]},2).to({state:[{t:this.shape_17},{t:this.shape_16}]},2).to({state:[{t:this.shape_19},{t:this.shape_18}]},2).to({state:[{t:this.shape_21},{t:this.shape_20}]},2).to({state:[{t:this.shape_13,p:{x:-15.0206}},{t:this.shape_12,p:{x:-19.7636}}]},2).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-213.6,-216.7,301.4,260.09999999999997);


(lib.sun = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.sun1();
	this.instance.setTransform(0,64.2,1,1,0,0,0,64.2,64.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({rotation:-0.0924,x:28.05,y:50},0).wait(1).to({rotation:0.121,x:57.05,y:35.35},0).wait(1).to({rotation:0.4624,x:86.35,y:20.65},0).wait(1).to({rotation:0.8792,x:116.05,y:6.1},0).wait(1).to({rotation:1.3535,x:146.15,y:-8.4},0).wait(1).to({rotation:1.8789,x:176.6,y:-22.75},0).wait(1).to({rotation:2.4558,x:207.45,y:-36.85},0).wait(1).to({rotation:3.0866,x:238.6,y:-50.8},0).wait(1).to({rotation:3.7777,x:270.2,y:-64.45},0).wait(1).to({rotation:4.537,x:302.2,y:-77.8},0).wait(1).to({rotation:5.3762,x:334.75,y:-90.9},0).wait(1).to({rotation:6.3103,x:367.75,y:-103.55},0).wait(1).to({rotation:7.3558,x:401.2,y:-115.75},0).wait(1).to({rotation:8.5352,x:435.15,y:-127.3},0).wait(1).to({rotation:9.8827,x:469.65,y:-138.3},0).wait(1).to({rotation:11.4355,x:504.7,y:-148.4},0).wait(1).to({rotation:13.2519,x:540.35,y:-157.65},0).wait(1).to({rotation:15.412,x:576.5,y:-165.65},0).wait(1).to({rotation:18.0226,x:613.25,y:-172.25},0).wait(1).to({rotation:21.2528,x:650.65,y:-176.95},0).wait(1).to({rotation:25.3219,x:688.3,y:-179.3},0).wait(1).to({rotation:28.1993,x:726.15,y:-179.15},0).wait(1).to({rotation:30.186,x:764.65,y:-177.5},0).wait(1).to({rotation:31.8279,x:803.35,y:-174.7},0).wait(1).to({rotation:33.2219,x:842.25,y:-170.8},0).wait(1).to({rotation:34.4328,x:881.3,y:-165.95},0).wait(1).to({rotation:35.5042,x:920.55,y:-160.35},0).wait(1).to({rotation:36.4709,x:960.1,y:-153.95},0).wait(1).to({rotation:37.3574,x:999.7,y:-146.9},0).wait(1).to({rotation:38.1834,x:1039.4,y:-139.2},0).wait(1).to({rotation:38.9689,x:1079.4,y:-130.9},0).wait(1).to({rotation:39.7305,x:1119.45,y:-121.95},0).wait(1).to({rotation:40.4867,x:1159.85,y:-112.4},0).wait(1).to({rotation:41.2581,x:1200.3,y:-102.3},0).wait(1).to({rotation:42.0765,x:1241,y:-91.55},0).wait(1).to({rotation:42.9894,x:1281.65,y:-80.05},0).wait(1).to({rotation:44.0911,x:1322.5,y:-67.85},0).wait(1).to({rotation:45.609,x:1363.1,y:-54.6},0).wait(1).to({rotation:48.3523,x:1403.4,y:-40},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.2,-243.6,1531.8,372);


(lib.picture = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_74 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(74).call(this.frame_74).wait(1));

	// Layer_1
	this.picture_mc = new lib.pic();
	this.picture_mc.name = "picture_mc";
	this.picture_mc.setTransform(0,0,1,1,0,0,0,45.3,67.7);

	this.timeline.addTween(cjs.Tween.get(this.picture_mc).wait(1).to({rotation:1.1538,x:0.05,y:0.05},0).wait(1).to({rotation:2.3077,x:0,y:0},0).wait(1).to({rotation:3.4615,y:0.05},0).wait(1).to({rotation:4.6153},0).wait(1).to({rotation:5.7692,y:0},0).wait(1).to({rotation:6.923},0).wait(1).to({rotation:8.0769,x:0.05,y:0.05},0).wait(1).to({rotation:9.2307,x:0,y:0},0).wait(1).to({rotation:10.3845},0).wait(1).to({rotation:11.5384,x:0.05,y:0.05},0).wait(1).to({rotation:12.6922},0).wait(1).to({rotation:13.846},0).wait(1).to({rotation:14.9999,y:0},0).wait(1).to({rotation:16.1537,x:0,y:0.05},0).wait(1).to({rotation:17.3075},0).wait(1).to({rotation:18.4614,y:0},0).wait(1).to({rotation:19.6152},0).wait(1).to({rotation:20.769,x:0.05},0).wait(1).to({rotation:21.9229,x:0},0).wait(1).to({rotation:23.0767,y:0.05},0).wait(1).to({rotation:24.2306},0).wait(1).to({rotation:25.3844,x:0.05,y:0},0).wait(1).to({rotation:26.5382,y:1.9},0).wait(1).to({rotation:27.6921,y:3.8},0).wait(1).to({rotation:28.8459,y:5.65},0).wait(1).to({rotation:29.9997,y:7.55},0).wait(1).to({rotation:31.1536,y:9.45},0).wait(1).to({rotation:32.3074,x:0,y:11.3},0).wait(1).to({rotation:33.4612,y:13.25},0).wait(1).to({rotation:34.6151,y:15.1},0).wait(1).to({rotation:35.7689,y:17},0).wait(1).to({rotation:36.9227,y:18.8},0).wait(1).to({rotation:38.0766,x:-0.05,y:20.75},0).wait(1).to({rotation:39.2304,x:0,y:22.6},0).wait(1).to({rotation:40.3843,y:24.5},0).wait(1).to({rotation:41.5381,x:-0.05,y:26.35},0).wait(1).to({rotation:42.6919,x:0,y:28.25},0).wait(1).to({rotation:43.8458,x:-0.05,y:30.2},0).wait(1).to({rotation:44.9996,x:0,y:32},0).wait(1).to({rotation:43.4479,y:31.5},0).wait(1).to({rotation:41.8962,x:-0.05,y:31},0).wait(1).to({rotation:40.3445,x:0,y:30.5},0).wait(1).to({rotation:38.7928,y:29.95},0).wait(1).to({rotation:37.241,y:29.45},0).wait(1).to({rotation:35.6893,y:28.95},0).wait(1).to({rotation:34.1376,x:-0.05,y:28.4},0).wait(1).to({rotation:32.5859,x:0,y:27.9},0).wait(1).to({rotation:31.0342,y:27.35},0).wait(1).to({rotation:29.4825,x:0.05,y:26.85},0).wait(1).to({rotation:27.9308,x:0,y:26.3},0).wait(1).to({rotation:26.3791,y:25.85},0).wait(1).to({rotation:24.8274,y:25.3},0).wait(1).to({rotation:23.2757,y:24.8},0).wait(1).to({rotation:21.7239,x:0.05,y:24.25},0).wait(1).to({rotation:20.1722,x:0,y:23.75},0).wait(1).to({rotation:18.6205,x:0.05,y:23.2},0).wait(1).to({rotation:17.0688,y:22.7},0).wait(1).to({rotation:15.5171,y:22.2},0).wait(1).to({rotation:13.9654,x:0,y:21.7},0).wait(1).to({rotation:12.4137,x:0.05,y:21.15},0).wait(1).to({rotation:10.862,y:20.65},0).wait(1).to({rotation:9.3103,x:0,y:20.15},0).wait(1).to({rotation:7.7586,x:0.05,y:19.6},0).wait(1).to({rotation:6.2068,y:19.1},0).wait(1).to({rotation:4.6551,x:0,y:18.6},0).wait(1).to({rotation:3.1034,x:0.05,y:18.05},0).wait(1).to({rotation:1.5517,x:0,y:17.55},0).wait(1).to({rotation:0,y:0},0).wait(7));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-84.8,-85.5,169.7,202.4);


(lib.fox = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.foxs();
	this.instance.setTransform(-916.65,-167.3,1,1,0,0,0,106.4,123.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({regY:123.1,rotation:0.9459,x:-855.3,y:-191.85},0).wait(1).to({rotation:1.9485,x:-794.4,y:-215},0).wait(1).to({rotation:2.9885,x:-733.9,y:-236.75},0).wait(1).to({rotation:4.0686,x:-673.9,y:-257.1},0).wait(1).to({rotation:5.1898,x:-614.4,y:-276},0).wait(1).to({rotation:6.3535,x:-555.3,y:-293.45},0).wait(1).to({rotation:7.5612,x:-496.75,y:-309.45},0).wait(1).to({rotation:8.8157,x:-438.6,y:-324},0).wait(1).to({rotation:10.1157,x:-381.05,y:-337.05},0).wait(1).to({rotation:11.4652,x:-323.95,y:-348.6},0).wait(1).to({rotation:12.8641,x:-267.4,y:-358.65},0).wait(1).to({rotation:14.3133,x:-211.45,y:-367.2},0).wait(1).to({rotation:15.8138,x:-156,y:-374.15},0).wait(1).to({rotation:17.3662,x:-101.05,y:-379.6},0).wait(1).to({rotation:18.9708,x:-46.7,y:-383.5},0).wait(1).to({rotation:20.6286,x:7.15,y:-385.75},0).wait(1).to({rotation:22.3394,x:60.25,y:-386.5},0).wait(1).to({rotation:24.1001,x:112.9,y:-385.6},0).wait(1).to({rotation:25.913,x:164.9,y:-383.1},0).wait(1).to({rotation:27.7749,x:216.35,y:-378.9},0).wait(1).to({rotation:29.6839,x:267.15,y:-373.1},0).wait(1).to({rotation:31.6384,x:317.4,y:-365.7},0).wait(1).to({rotation:33.6344,x:366.9,y:-356.55},0).wait(1).to({rotation:35.6675,x:415.8,y:-345.85},0).wait(1).to({rotation:37.7365,x:464.1,y:-333.4},0).wait(1).to({rotation:39.8339,x:511.7,y:-319.2},0).wait(1).to({rotation:41.9568,x:558.6,y:-303.35},0).wait(1).to({rotation:44.0988,x:604.9,y:-285.8},0).wait(1).to({rotation:46.2542,x:650.45,y:-266.5},0).wait(1).to({rotation:48.4172,x:695.3,y:-245.45},0).wait(1).to({rotation:50.5828,x:739.55,y:-222.7},0).wait(1).to({rotation:52.744,x:782.95,y:-198.15},0).wait(1).to({rotation:54.8948,x:825.8,y:-171.85},0).wait(1).to({rotation:57.0305,x:867.75,y:-143.75},0).wait(1).to({rotation:59.1445,x:909.05,y:-113.9},0).wait(1).to({rotation:61.2316,x:949.65,y:-82.3},0).wait(1).to({rotation:63.2873,x:989.45,y:-48.85},0).wait(1).to({rotation:65.3071,x:1028.45,y:-13.65},0).wait(1).to({rotation:67.2893,x:1066.75,y:23.5},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1023,-489.8,2236.7,644.4);


(lib.cloud = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.clouds_mc = new lib.clouds();
	this.clouds_mc.name = "clouds_mc";
	this.clouds_mc.setTransform(-249.9,37.5,1,1,0,0,0,183.7,83.7);

	this.timeline.addTween(cjs.Tween.get(this.clouds_mc).wait(1).to({regX:183.8,regY:83.8,rotation:1.4341,x:-218.75,y:30.65},0).wait(1).to({rotation:2.1807,x:-187.55,y:24.3},0).wait(1).to({rotation:2.704,x:-156.35,y:18.2},0).wait(1).to({rotation:3.1286,x:-125.2,y:12.45},0).wait(1).to({rotation:3.5026,x:-94.25,y:6.95},0).wait(1).to({rotation:3.8508,x:-63.35,y:1.6},0).wait(1).to({rotation:4.1873,x:-32.55,y:-3.5},0).wait(1).to({rotation:4.5216,x:-1.9,y:-8.4},0).wait(1).to({rotation:4.8623,x:28.6,y:-13.1},0).wait(1).to({rotation:5.2151,x:59,y:-17.6},0).wait(1).to({rotation:5.5874,x:89.25,y:-21.9},0).wait(1).to({rotation:5.9856,x:119.4,y:-25.95},0).wait(1).to({rotation:6.4189,x:149.45,y:-29.8},0).wait(1).to({rotation:6.8972,x:179.3,y:-33.35},0).wait(1).to({rotation:7.4341,x:209.1,y:-36.6},0).wait(1).to({rotation:8.0469,x:238.75,y:-39.55},0).wait(1).to({rotation:8.7615,x:268.3,y:-42.2},0).wait(1).to({rotation:9.6166,x:297.75,y:-44.4},0).wait(1).to({rotation:10.4516,x:327,y:-46.1},0).wait(1).to({rotation:11.1303,x:356.2,y:-47.45},0).wait(1).to({rotation:11.6957,x:385.2,y:-48.5},0).wait(1).to({rotation:12.1803,x:414.05,y:-49.2},0).wait(1).to({rotation:12.604,x:442.85,y:-49.75},0).wait(1).to({rotation:12.9811,x:471.5,y:-50.05},0).wait(1).to({rotation:13.322,x:499.95,y:-50.2},0).wait(1).to({rotation:13.6351,x:528.25,y:-50.15},0).wait(1).to({rotation:13.9266,x:556.45,y:-50},0).wait(1).to({rotation:14.2015,x:584.45,y:-49.7},0).wait(1).to({rotation:14.465,x:612.25,y:-49.3},0).wait(1).to({rotation:14.7217,x:640.05,y:-48.75},0).wait(1).to({rotation:14.9755,x:667.65,y:-48.05},0).wait(1).to({rotation:15.232,x:695.1,y:-47.25},0).wait(1).to({rotation:15.4973,x:722.35,y:-46.35},0).wait(1).to({rotation:15.7802,x:749.45,y:-45.3},0).wait(1).to({rotation:16.0938,x:776.5,y:-44.15},0).wait(1).to({rotation:16.4608,x:803.3,y:-42.8},0).wait(1).to({rotation:16.927,x:830,y:-41.35},0).wait(1).to({rotation:17.6037,x:856.5,y:-39.5},0).wait(1).to({rotation:18.8893,x:882.35,y:-37.4},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-433.3,-152.3,1493.8,293.1);


(lib.bunnyears = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_38 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(38).call(this.frame_38).wait(1));

	// Layer_1
	this.ears_mc = new lib.rabbit();
	this.ears_mc.name = "ears_mc";
	this.ears_mc.setTransform(0,121.8,1,1,0,0,0,69.4,110.7);

	this.timeline.addTween(cjs.Tween.get(this.ears_mc).wait(1).to({y:72.5},0).wait(1).to({y:23.2},0).wait(1).to({y:26.25},0).wait(1).to({y:29.25},0).wait(1).to({y:32.3},0).wait(1).to({y:35.3},0).wait(1).to({y:38.3},0).wait(1).to({y:41.35},0).wait(1).to({y:44.35},0).wait(1).to({y:47.35},0).wait(1).to({y:50.4},0).wait(1).to({y:53.4},0).wait(1).to({y:56.4},0).wait(1).to({y:59.45},0).wait(1).to({y:62.45},0).wait(1).to({y:65.45},0).wait(1).to({y:68.5},0).wait(1).to({y:71.5},0).wait(1).to({y:74.5},0).wait(1).to({y:77.55},0).wait(1).to({y:80.55},0).wait(1).to({y:83.55},0).wait(1).to({y:86.6},0).wait(1).to({y:89.6},0).wait(1).to({y:92.6},0).wait(1).to({y:95.65},0).wait(1).to({y:98.65},0).wait(1).to({y:101.65},0).wait(1).to({y:104.7},0).wait(1).to({y:107.7},0).wait(1).to({y:121.8},0).wait(8));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69.4,-87.5,138.8,320);


(lib._2chair = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_49 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(49).call(this.frame_49).wait(1));

	// Layer_1
	this.chair2_mc = new lib.chair2();
	this.chair2_mc.name = "chair2_mc";
	this.chair2_mc.setTransform(0,0,1,1,0,0,0,102.1,175.1);

	this.timeline.addTween(cjs.Tween.get(this.chair2_mc).wait(3).to({x:14.45},0).wait(1).to({x:28.9},0).wait(1).to({x:43.3},0).wait(1).to({x:57.75},0).wait(1).to({x:72.15},0).wait(1).to({x:86.6},0).wait(1).to({x:101.05},0).wait(1).to({x:115.4},0).wait(1).to({x:129.85},0).wait(1).to({x:144.3},0).wait(1).to({x:139.9},0).wait(1).to({x:135.5},0).wait(1).to({x:131.1},0).wait(1).to({x:126.7},0).wait(1).to({x:122.3},0).wait(1).to({x:117.95},0).wait(1).to({x:113.55},0).wait(1).to({x:109.15},0).wait(1).to({x:104.75},0).wait(1).to({x:100.4},0).wait(1).to({x:96.05},0).wait(1).to({x:91.65},0).wait(1).to({x:87.25},0).wait(1).to({x:82.85},0).wait(1).to({x:78.45},0).wait(1).to({x:74.05},0).wait(1).to({x:69.7},0).wait(1).to({x:65.3},0).wait(1).to({x:60.9},0).wait(1).to({x:56.5},0).wait(1).to({x:52.1},0).wait(1).to({x:47.75},0).wait(1).to({x:43.35},0).wait(1).to({x:38.95},0).wait(1).to({x:34.55},0).wait(1).to({x:30.15},0).wait(1).to({x:25.75},0).wait(1).to({x:21.4},0).wait(1).to({x:17},0).wait(1).to({x:12.6},0).wait(1).to({x:0},0).wait(7));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-102.1,-175.1,348.6,350.2);


(lib._1chair = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_50 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(50).call(this.frame_50).wait(1));

	// Layer_1
	this.chair1_mc = new lib.chair1();
	this.chair1_mc.name = "chair1_mc";
	this.chair1_mc.setTransform(0,0,1,1,0,0,0,102.1,175.1);

	this.timeline.addTween(cjs.Tween.get(this.chair1_mc).wait(3).to({x:-13.25},0).wait(1).to({x:-26.5},0).wait(1).to({x:-39.75},0).wait(1).to({x:-53},0).wait(1).to({x:-66.25},0).wait(1).to({x:-79.5},0).wait(1).to({x:-92.8},0).wait(1).to({x:-90.15},0).wait(1).to({x:-87.55},0).wait(1).to({x:-84.95},0).wait(1).to({x:-82.35},0).wait(1).to({x:-79.75},0).wait(1).to({x:-77.15},0).wait(1).to({x:-74.55},0).wait(1).to({x:-71.95},0).wait(1).to({x:-69.35},0).wait(1).to({x:-66.75},0).wait(1).to({x:-64.15},0).wait(1).to({x:-61.55},0).wait(1).to({x:-58.95},0).wait(1).to({x:-56.35},0).wait(1).to({x:-53.75},0).wait(1).to({x:-51.15},0).wait(1).to({x:-48.55},0).wait(1).to({x:-45.95},0).wait(1).to({x:-43.35},0).wait(1).to({x:-40.75},0).wait(1).to({x:-38.15},0).wait(1).to({x:-35.55},0).wait(1).to({x:-32.95},0).wait(1).to({x:-30.35},0).wait(1).to({x:-27.75},0).wait(1).to({x:-25.15},0).wait(1).to({x:-22.55},0).wait(1).to({x:-19.95},0).wait(1).to({x:-17.35},0).wait(1).to({x:-14.75},0).wait(1).to({x:-12.15},0).wait(1).to({x:-9.55},0).wait(1).to({x:-6.95},0).wait(1).to({x:-4.35},0).wait(1).to({x:-1.75},0).wait(1).to({x:0},0).wait(6));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-194.9,-175.1,297.1,350.2);


(lib.background = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// text
	this.instance = new lib.CachedBmp_33();
	this.instance.setTransform(3693.25,-68.25,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// picture
	this.picture_mc = new lib.picture();
	this.picture_mc.name = "picture_mc";
	this.picture_mc.setTransform(2555,-683.65);

	this.timeline.addTween(cjs.Tween.get(this.picture_mc).wait(1));

	// middle
	this.chair2_mc = new lib._2chair();
	this.chair2_mc.name = "chair2_mc";
	this.chair2_mc.setTransform(2391.65,-337.55);

	this.chair1_mc = new lib._1chair();
	this.chair1_mc.name = "chair1_mc";
	this.chair1_mc.setTransform(1618.45,-319.25);

	this.instance_1 = new lib.CachedBmp_34();
	this.instance_1.setTransform(102.5,-975.75,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.chair1_mc},{t:this.chair2_mc}]}).wait(1));

	// back
	this.instance_2 = new lib.CachedBmp_35();
	this.instance_2.setTransform(558.9,-1079.35,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// wallandfloor
	this.instance_3 = new lib.CachedBmp_36();
	this.instance_3.setTransform(0,-1082.6,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// bunnyears
	this.ears_mc = new lib.bunnyears();
	this.ears_mc.name = "ears_mc";
	this.ears_mc.setTransform(2075,-663.45);

	this.timeline.addTween(cjs.Tween.get(this.ears_mc).wait(1));

	// scenery
	this.instance_4 = new lib.CachedBmp_37();
	this.instance_4.setTransform(1646.7,-880.95,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(1));

	// clouds
	this.cloud_mc = new lib.cloud();
	this.cloud_mc.name = "cloud_mc";
	this.cloud_mc.setTransform(1675.85,-801.05);

	this.timeline.addTween(cjs.Tween.get(this.cloud_mc).wait(1));

	// sun
	this.sun_mc = new lib.sun();
	this.sun_mc.name = "sun_mc";
	this.sun_mc.setTransform(1150.9,-692.55);

	this.timeline.addTween(cjs.Tween.get(this.sun_mc).wait(1));

	// sky
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#83BDFF").s().p("EnCABUYMAAAiovMOEBAAAMAAACovg");
	this.shape.setTransform(2000.0033,-540,0.6944,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.background, new cjs.Rectangle(0,-1082.6,4000,1083), null);


// stage content:
(lib.murillo_finalProject = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,1];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		document.addEventListener("keydown", handleKeyDown);
		document.addEventListener("keyup", handleKeyUp);
		
		var root = this;
		var speed = 100
		
		function handleKeyDown(event) {
			console.log(root.background_mc.x);
			if (root.rabbit_mc.currentFrame == 11){
				root.rabbit_mc.gotoAndPlay("walking");
			}
				
			if (event.keyCode == 39 && root.background_mc.x > -2340) {
				root.rabbit_mc.scaleX = 1.3501;
				root.background_mc.x = root.background_mc.x - speed;
				
			}
			if (event.keyCode == 37 && root.background_mc.x < 960) {
				root.rabbit_mc.scaleX = -1.3501;
				root.background_mc.x = root.background_mc.x + speed;
			}
		}
		
		function handleKeyUp(event) {
			root.rabbit_mc.gotoAndPlay("standing");
		}
		
		this.background_mc.ears_mc.addEventListener("click",handleClickEars);
		
		function handleClickEars(event){
			var pop2_snd = createjs.Sound.play("pop2");
			root.background_mc.ears_mc.play();
		}
		
		this.play_btn.addEventListener("click",handleClickPlayButton);
		
		function handleClickPlayButton(event){
			var music_snd = createjs.Sound.play("music");
			root.play();
		}
		
		this.background_mc.chair1_mc.addEventListener("click",handleClickChair1);
		
		function handleClickChair1(event){
			var sliding_snd = createjs.Sound.play("sliding");
			root.background_mc.chair1_mc.play();
		}
		
		this.background_mc.chair2_mc.addEventListener("click",handleClickChair2);
		
		function handleClickChair2(event){
			var sliding_snd = createjs.Sound.play("sliding");
			root.background_mc.chair2_mc.play();
		}
		
		this.background_mc.picture_mc.addEventListener("click",handleClickPicture);
		
		function handleClickPicture(event){
			var creaking_snd = createjs.Sound.play("creaking");
			root.background_mc.picture_mc.play();
		}
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// text
	this.instance = new lib.CachedBmp_27();
	this.instance.setTransform(247.7,444.8,0.5,0.5);

	this.instance_1 = new lib.CachedBmp_26();
	this.instance_1.setTransform(809.6,370.25,0.5,0.5);

	this.instance_2 = new lib.CachedBmp_25();
	this.instance_2.setTransform(0.05,149.8,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).to({state:[]},1).wait(1));

	// button
	this.play_btn = new lib.carrot();
	this.play_btn.name = "play_btn";
	this.play_btn.setTransform(1685.5,829.15);

	this.timeline.addTween(cjs.Tween.get(this.play_btn).to({_off:true},1).wait(1));

	// sign
	this.instance_3 = new lib.CachedBmp_32();
	this.instance_3.setTransform(149.75,766.1,0.5,0.5);

	this.instance_4 = new lib.CachedBmp_31();
	this.instance_4.setTransform(181.4,710.65,0.5,0.5);

	this.instance_5 = new lib.CachedBmp_30();
	this.instance_5.setTransform(194.7,654.05,0.5,0.5);

	this.instance_6 = new lib.CachedBmp_29();
	this.instance_6.setTransform(194.7,603.65,0.5,0.5);

	this.instance_7 = new lib.CachedBmp_28();
	this.instance_7.setTransform(128.45,595.05,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_7},{t:this.instance_6},{t:this.instance_5},{t:this.instance_4},{t:this.instance_3}]}).to({state:[]},1).wait(1));

	// front
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006600").s().p("EhpcAX4MAAAgu3UBg7gF+BK3AitMAnHASIg");
	this.shape.setTransform(674.85,927.1907);

	this.timeline.addTween(cjs.Tween.get(this.shape).to({_off:true},1).wait(1));

	// middle
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#003107").s().p("EiV+AkhIgBrVUEUMhl3AXzBCVMAAAAu3g");
	this.shape_1.setTransform(960,846.3175);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).to({_off:true},1).wait(1));

	// fox
	this.instance_8 = new lib.fox();
	this.instance_8.setTransform(735.05,878.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).to({_off:true},1).wait(1));

	// back
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#001A04").s().p("EiV/AoUMAAAgu3UB9nhDhCuYBDhMAAAAu3g");
	this.shape_2.setTransform(960,821.9659);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).to({_off:true},1).wait(1));

	// walking
	this.rabbit_mc = new lib.walking();
	this.rabbit_mc.name = "rabbit_mc";
	this.rabbit_mc.setTransform(337.85,835.7,1.3501,1.2034,0,0,0,-11.1,-84.4);
	this.rabbit_mc._off = true;

	this.timeline.addTween(cjs.Tween.get(this.rabbit_mc).wait(1).to({_off:false},0).wait(1));

	// background
	this.background_mc = new lib.background();
	this.background_mc.name = "background_mc";
	this.background_mc.setTransform(960,540,1,1,0,0,0,960,-540);
	this.background_mc._off = true;

	this.timeline.addTween(cjs.Tween.get(this.background_mc).wait(1).to({_off:false},0).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(672,537.4,3328,543.0000000000001);
// library properties:
lib.properties = {
	id: 'ABD368BEC3FE4584B1FF4CF615B373A7',
	width: 1920,
	height: 1080,
	fps: 24,
	color: "#A2CCFF",
	opacity: 0.86,
	manifest: [
		{src:"images/CachedBmp_36.png", id:"CachedBmp_36"},
		{src:"images/CachedBmp_35.png", id:"CachedBmp_35"},
		{src:"images/CachedBmp_34.png", id:"CachedBmp_34"},
		{src:"images/CachedBmp_27.png", id:"CachedBmp_27"},
		{src:"images/CachedBmp_26.png", id:"CachedBmp_26"},
		{src:"images/CachedBmp_25.png", id:"CachedBmp_25"},
		{src:"images/murillo_finalProject_atlas_1.png", id:"murillo_finalProject_atlas_1"},
		{src:"sounds/music.mp3", id:"music"},
		{src:"sounds/creaking.mp3", id:"creaking"},
		{src:"sounds/pop2.mp3", id:"pop2"},
		{src:"sounds/sliding.mp3", id:"sliding"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['ABD368BEC3FE4584B1FF4CF615B373A7'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;